services:
  rpa-mit-manual-templates-api:
    build:
      target: development
    image: rpa-mit-manual-templates-api-development
    container_name: rpa-mit-manual-templates-api-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./Rpa.Mit.Manual.Templates.Api.sln:/home/dotnet/Rpa.Mit.Manual.Templates.Api.sln
      - ./src/Rpa.Mit.Manual.Templates.Api.Core:/home/dotnet/src/Rpa.Mit.Manual.Templates.Api.Core
      - ./test/Rpa.Mit.Manual.Templates.Api.Core.Tests:/home/dotnet/test/Rpa.Mit.Manual.Templates.Api.Core.Tests
      - ./src/Rpa.Mit.Manual.Templates.Api.Api:/home/dotnet/src/Rpa.Mit.Manual.Templates.Api.Api
      - ./test/Rpa.Mit.Manual.Templates.Api.Api.Tests:/home/dotnet/test/Rpa.Mit.Manual.Templates.Api.Api.Tests
      - ./test/Rpa.Mit.Manual.Templates.Api.Api.Tests/test-output:/home/dotnet/test/Rpa.Mit.Manual.Templates.Api.Api.Tests/test-output
      - ./test/Rpa.Mit.Manual.Templates.Api.Core.Tests/test-output:/home/dotnet/test/Rpa.Mit.Manual.Templates.Api.Core.Tests/test-output
      - ./test/Rpa.Mit.Manual.Templates.Api.Api.Integration.Tests/test-output:/home/dotnet/test/Rpa.Mit.Manual.Templates.Api.Api.Integration.Tests/test-output
 
