services:
  rpa-mit-manual-templates-api:
    build:
      context: .
      target: production
    image: rpa-mit-manual-templates-api
    container_name: rpa-mit-manual-templates-api
    depends_on:
      - rpa_mit_invoices-postgres
    environment:
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APPINSIGHTS_CLOUDROLE: rpa-mit-manual-templates-api-local
      POSTGRES_DB: ${POSTGRES_DB:-rpa_mit_invoices}
      POSTGRES_HOST: ${POSTGRES_HOST:-rpa-mit-invoices-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ghjiUIbfds345}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  rpa_mit_invoices:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: rpa_mit_invoices
      POSTGRES_PASSWORD: ghjiUIbfds345
      POSTGRES_USERNAME: postgres
