INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P1 Penalties','SOS360','Penalty','DF'),
	 ('G00 - GROSS VALUE OF CLAIM','SOS310','Irregularity','DA,DF'),
	 ('G00 - GROSS VALUE OF CLAIM','SOS330','Admin Error','DA,DF'),
	 ('R00 Crisis reserve distribution','SOS217','Admin Error','DA'),
	 ('R00 Crisis reserve distribution','SOS218','Irregularity','DA'),
	 ('P12 Crisis reserve reduction','SOS267','Admin Error','DA'),
	 ('P12 Crisis reserve reduction','SOS268','Irregularity','DA'),
	 ('P15 FDM Budget Adjustment','SOS316','Irregularity','DA'),
	 ('P15 FDM Budget Adjustment','SOS336','Admin Error','DA'),
	 ('Three Year Penalty','SOS365','Irregularity','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P02 - Over declaration penalty','SOS430','Irregularity','DA'),
	 ('P03 Non-compliance penalty','SOS431','Irregularity','DA'),
	 ('P04 Administrative penalty','SOS432','Irregularity','DA'),
	 ('P05 Late claim submission penalty','SOS433','Irregularity','DA'),
	 ('P06 Late change penalty','SOS434','Irregularity','DA'),
	 ('P07 Late claim for entitlement NR penalty','SOS435','Irregularity','DA'),
	 ('P08 Non declaration of land penalty','SOS436','Irregularity','DA'),
	 ('P09 Linear reduction supplement','SOS437','Irregularity','DA'),
	 ('P10 Breach of Ceiling LR penalty','SOS438','Irregularity','DA'),
	 ('P13 5% reduction over €150,000','SOS439','Irregularity','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P16 15% reduction over €150,000','SOS440','Irregularity','DA'),
	 ('P17 30% reduction over €200,000','SOS441','Irregularity','DA'),
	 ('P18 55% reduction over €250,000','SOS442','Irregularity','DA'),
	 ('P19 100% reduction over €150,000','SOS443','Irregularity','DA'),
	 ('P20 100% reduction over €300,000','SOS443','Irregularity','DA'),
	 ('P21 100% reduction over €600,000','SOS443','Irregularity','DA'),
	 ('P14 Cross compliance penalty','SOS444','Irregularity','DA'),
	 ('P01 - Young Farmer false evidence penalty','SOS445','Irregularity','DA'),
	 ('P11 Reduction due to Net Ceiling Scaleback','SOS446','Irregularity','DA'),
	 ('P02 - Over declaration penalty','SOS450','Admin Error','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P03 Non-compliance penalty','SOS451','Admin Error','DA'),
	 ('P04 Administrative penalty','SOS452','Admin Error','DA'),
	 ('P05 Late claim submission penalty','SOS453','Admin Error','DA'),
	 ('P06 Late change penalty','SOS454','Admin Error','DA'),
	 ('P07 Late claim for entitlement NR penalty','SOS455','Admin Error','DA'),
	 ('P08 Non declaration of land penalty','SOS456','Admin Error','DA'),
	 ('P09 Linear reduction supplement','SOS457','Admin Error','DA'),
	 ('P10 Breach of Ceiling LR penalty','SOS458','Admin Error','DA'),
	 ('P13 5% reduction over €150,000','SOS459','Admin Error','DA'),
	 ('P16 15% reduction over €150,000','SOS460','Admin Error','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P17 30% reduction over €200,000','SOS461','Admin Error','DA'),
	 ('P18 55% reduction over €250,000','SOS462','Admin Error','DA'),
	 ('P19 100% reduction over €150,000','SOS463','Admin Error','DA'),
	 ('P20 100% reduction over €300,000','SOS463','Admin Error','DA'),
	 ('P21 100% reduction over €600,000','SOS463','Admin Error','DA'),
	 ('P14 Cross compliance penalty','SOS464','Admin Error','DA'),
	 ('P01 - Young Farmer false evidence penalty','SOS465','Admin Error','DA'),
	 ('P11 Reduction due to Net Ceiling Scaleback','SOS466','Admin Error','DA'),
	 ('BPS Progressive Red Band 1','SOS471','NA','DA'),
	 ('BPS Progressive Red Band 2','SOS472','NA','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('BPS Progressive Red Band 3','SOS473','NA','DA'),
	 ('BPS Progressive Red Band 4','SOS474','NA','DA'),
	 ('Admin error - (DRD)','SOS750','Admin Error','DA'),
	 ('Gross Value of Claim','SOS330','Admin Error','IP'),
	 ('EX0 - Interim Payment','SOS355','Exchequer','IP'),
	 ('Ex Gratia Interest Recovery','SOS245','Exchequer','XG'),
	 ('Ex Gratia Recovery','SOS240','Exchequer','XG'),
	 ('Defra reimbursement','SOO930','Admin Error','BK'),
	 ('Interest (P1) on scheme receivable - Irregularity','SRO380','Irregularity','INT'),
	 ('Interest (P1) on scheme receivable - Admin error','SRO381','Admin Error','INT');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Interest (P1) on scheme receivable - Cross compliance','SRO382','Irregularity','INT'),
	 ('Interest (P1) on scheme receivable - Penalty','SRO383','Irregularity','INT'),
	 ('Interest (P2) - non-convergence','SRO390','Irregularity','INT'),
	 ('Interest (P2) - convergence','SRO391','Irregularity','INT'),
	 ('Interest (P2) - VM','SRO392','Irregularity','INT'),
	 ('Interest (P2) - New CM - non-convergence','SRO393','Irregularity','INT'),
	 ('Interest (P2) - New CM - convergence','SRO394','Irregularity','INT'),
	 ('Interest (P2) - EERP - non-convergence','SRO395','Irregularity','INT'),
	 ('Interest (P2) - Core EAFRD - Axis 2 - non-convergence','SRO400','Irregularity','INT'),
	 ('Interest (P2) - Core EAFRD - Axis 2 - convergence','SRO401','Irregularity','INT');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Interest (P2) - 2014 Transitional Modulation - Axis 2','SRO402','Irregularity','INT'),
	 ('Interest (P2) P1 to P2 Transfer - Axis','SRO403','Irregularity','INT'),
	 ('Interest (P2) - New Programme Axis 1 & 3','SRO404','Irregularity','INT'),
	 ('Interest - State Aid ','SRO420','Irregularity','INT'),
	 ('National Modulation Deduction','SOM620','Irregularity','SPS'),
	 ('EC Modulation Deduction','SOM625','Irregularity','SPS'),
	 ('National Modulation Deduction','SOM640','Admin Error','SPS'),
	 ('EC Modulation Deduction','SOM645','Admin Error','SPS'),
	 ('P12 Crisis reserve reduction','SOS267','Admin Error','SPS'),
	 ('P12 Crisis reserve reduction','SOS268','Irregularity','SPS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Three Year Penalty','SOS365','Irregularity','SPS'),
	 ('Irregularity Debt','SOS310','Irregularity','SPS'),
	 ('FDM - 0142','SOS316','Irregularity','SPS'),
	 ('FDM - 0143','SOS326','Admin Error','SPS'),
	 ('Admin Debt','SOS330','Admin Error','SPS'),
	 ('FDM - 0140','SOS336','Admin Error','SPS'),
	 ('Penalties','SOS360','Irregularity','SPS'),
	 ('Cross Compliance Penalty','SOS444','Irregularity','SPS'),
	 ('CMO Recharge','SRO150','CMO Recharge','TR'),
	 ('G00 - GROSS VALUE OF CLAIM','SOS310','Irregularity','TR');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('G00 - GROSS VALUE OF CLAIM','SOS330','Admin Error','TR'),
	 ('EX0 - Interim Payment','SOS355','Exchequer','TR'),
	 ('Top-up Payment','SOS213','School Milk Top-up Funding','TR'),
	 ('Penalties','SOS360','Irregularity','TR'),
	 ('Intervention Operating Cost Recoveries','SOI761','Irregularity','TR'),
	 ('Intervention Sales','SRI710','Irregularity','TR'),
	 ('Own Resources','SOO750',NULL,'TR'),
	 ('OPA Irregularity Recoveries','SOF820','Irregularity','OPA'),
	 ('OPA Admin Error Recoveries','SOF821','Admin Error','OPA'),
	 ('State Aid Standalone','SOS229',NULL,'FC');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P1 to P2 Transfer 100% EU','SOS273',NULL,'FC'),
	 ('New Programme','SOS384','Irregularity','FC'),
	 ('EAFRD- non-convergence','SOS320','Irregularity','FC'),
	 ('EAFRD - convergence','SOS321','Irregularity','FC'),
	 ('Modulation','SOS322','Irregularity','FC'),
	 ('Modulation','SOS342','Admin Error','FC'),
	 ('New Programme','SOS389','Admin Error','FC'),
	 ('VM - (ERD07)','SOS372','Irregularity','FC'),
	 ('Core EAFRD - non-Conv','SOS390','Penalty','FC'),
	 ('Core EAFRD - convergence','SOS391','Penalty','FC');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('2014 Transitional Modulation','SOS392','Penalty','FC'),
	 ('P1 to P2 Transfer','SOS393','Penalty','FC'),
	 ('Irregularities (P1)','SOS310','Irregularity','FC'),
	 ('New Programme','SOS394','Penalty','FC'),
	 ('2014 Transitional Modulation','SOS382','Irregularity','FCCS'),
	 ('P1 to P2 Transfer','SOS383','Irregularity','FCCS'),
	 ('2014 Transitional Modulation','SOS387','Admin Error','FCCS'),
	 ('P1 to P2 Transfer','SOS388','Admin Error','FCCS'),
	 ('State Aid Recovery','SOS352','Exchequer','FCCS'),
	 ('Over Declaration Penalty (P1 to P2 Capital) - P02','SOS530','Irregularity','FCCS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Over Declaration Reduction (P1 to P2 Capital) - P24','SOS531','Irregularity','FCCS'),
	 ('Late Claim Submission Penalty (P1 to P2 Revenue) - P05','SOS533','Irregularity','FCCS'),
	 ('Cross Compliance Penalty (P1 to P2 Revenue) - P14','SOS536','Irregularity','FCCS'),
	 ('RD Refusals Penalty (P1 to P2 Revenue) - P22','SOS537','Irregularity','FCCS'),
	 ('State Aid Over Declaration Penalty - P02','SOS553','Exchequer','FCCS'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS554','Exchequer','FCCS'),
	 ('Late Claim Submission Penalty (State Aid Revenue) - P05','SOS555','Exchequer','FCCS'),
	 ('Cross Compliance Penalty (State Aid Revenue) - P14','SOS558','Exchequer','FCCS'),
	 ('Over Declaration Penalty (P1 to P2 Capital) - P02','SOS570','Admin Error','FCCS'),
	 ('Over Declaration Reduction (P1 to P2 Capital) - P24','SOS571','Admin Error','FCCS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Over Declaration Penalty (P1 to P2 Revenue) - P02','SOS572','Admin Error','FCCS'),
	 ('Late Claim Submission Penalty (P1 to P2 Revenue) - P05','SOS573','Admin Error','FCCS'),
	 ('Cross Compliance Penalty (P1 to P2 Revenue) - P14','SOS576','Admin Error','FCCS'),
	 ('P1 to P2 Transfer','SOS393','Penalty','FCCS'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) - P24','SOS561','Irregularity','FCCS'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) - P24','SOS593','Admin Error','FCCS'),
	 ('Irregularity','SOS770','Irregularity','NEP1'),
	 ('Admin error','SOS750','Admin','NEP1'),
	 ('P1 to P2 Transfer','SOS383','Irregularity','RDPE'),
	 ('P1 to P2 Transfer','SOS388','Admin Error','RDPE');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P1 to P2 Transfer','SOS393','Penalty','RDPE'),
	 ('State Aid Recovery','SOS352','Exchequer','RDPE'),
	 ('EAFRD- non-convergence','SOS320','Irregularity','RDPE'),
	 ('EAFRD - convergence','SOS321','Irregularity','RDPE'),
	 ('EAFRD VM','SOS322','Irregularity','RDPE'),
	 ('New CM - non-convergence','SOS323','Irregularity','RDPE'),
	 ('New CM - convergence','SOS324','Irregularity','RDPE'),
	 ('EERP - non-convergence','SOS325','Irregularity','RDPE'),
	 ('EAFRD- non-convergence','SOS340','Admin Error','RDPE'),
	 ('EAFRD - convergence','SOS341','Admin Error','RDPE');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('EAFRD VM','SOS342','Admin Error','RDPE'),
	 ('New CM - non-convergence','SOS343','Admin Error','RDPE'),
	 ('New CM - convergence','SOS344','Admin Error','RDPE'),
	 ('EERP - non-convergence','SOS345','Admin Error','RDPE'),
	 ('State Aid Recovery','SOS352','Exchequer','RDPE'),
	 ('Admin error - (DRD)','SOS750','Admin Error','RDPE'),
	 ('Irregularity - (DRD)','SOS770','Irregularity','RDPE'),
	 ('Irregularity','SOS310 ','Irregularity','HE'),
	 ('Admin Error','SOS330 ','Admin Error','HE'),
	 ('2000-2006 Programme Funds','SOS310','Irregularity','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('2000-2006 Programme Funds','SOS330','Admin Error','NE-LS'),
	 ('2000-2006 Programme Funds','SOS360','Penalty','NE-LS'),
	 ('Three Year Penalty','SOS365','Penalty','NE-LS'),
	 ('EAFRD- non-convergence','SOS320','Irregularity','NE-LS'),
	 ('EAFRD - convergence','SOS321','Irregularity','NE-LS'),
	 ('Modulation','SOS322','Irregularity','NE-LS'),
	 ('New CM - non-convergence','SOS323','Irregularity','NE-LS'),
	 ('New CM - convergence','SOS324','Irregularity','NE-LS'),
	 ('EAFRD- non-convergence','SOS340','Admin Error','NE-LS'),
	 ('EAFRD - convergence','SOS341','Admin Error','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Modulation','SOS342','Admin Error','NE-LS'),
	 ('New CM - non-convergence','SOS343','Admin Error','NE-LS'),
	 ('New CM - convergence','SOS344','Admin Error','NE-LS'),
	 ('EAFRD- non-convergence','SOS370','Penalty','NE-LS'),
	 ('EAFRD - convergence','SOS371','Penalty','NE-LS'),
	 ('Modulation','SOS372','Penalty','NE-LS'),
	 ('New CM - non-convergence','SOS373','Penalty','NE-LS'),
	 ('New CM - convergence','SOS374','Penalty','NE-LS'),
	 ('Core EAFRD - non Conv','SOS390','Penalty','NE-LS'),
	 ('Core EAFRD - Conv','SOS391','Penalty','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('2014 Transitional Modulation','SOS392','Penalty','NE-LS'),
	 ('P1 to P2 Transfer','SOS393','Penalty','NE-LS'),
	 ('Three Year Penalty','SOS365','Penalty','NECS'),
	 ('Core EAFRD - Non Conv 75% EU','SOS380','Irregularity','NECS'),
	 ('Core EAFRD - Conv 85% EU','SOS381','Irregularity','NECS'),
	 ('2014 Transitional Modulation','SOS382','Irregularity','NECS'),
	 ('P1 to P2 Transfer','SOS383','Irregularity','NECS'),
	 ('Core EAFRD - Non Conv 75% EU','SOS385','Admin Error','NECS'),
	 ('Core EAFRD - Conv 85% EU','SOS386','Admin Error','NECS'),
	 ('2014 Transitional Modulation','SOS387','Admin Error','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P1 to P2 Transfer','SOS388','Admin Error','NECS'),
	 ('State Aid Recovery','SOS352','Exchequer','NECS'),
	 ('Over Declaration  (P1 to P2 Capital) - P02','SOS530','Irregularity','NECS'),
	 ('Over Declaration Reduction (P1 to P2 Capital) - P24','SOS531','Irregularity','NECS'),
	 ('Late Claim Submission  (P1 to P2 Revenue) - P05','SOS533','Irregularity','NECS'),
	 ('Late Change  (P1 to P2 Revenue) - P06','SOS534','Irregularity','NECS'),
	 ('Non Declaration of Land  (P1 to P2 Revenue) - P08','SOS535','Irregularity','NECS'),
	 ('Cross Compliance  (P1 to P2 Revenue) - P14','SOS536','Irregularity','NECS'),
	 ('RD Refusals  (P1 to P2 Revenue) - P22','SOS537','Irregularity','NECS'),
	 ('RD Withdrawals  (P1 to P2 Revenue) - P23','SOS538','Irregularity','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Over Declaration  (EAFRD Non Conv 75% EU) - P02','SOS539','Irregularity','NECS'),
	 ('Late Claim Submission  (EAFRD Non Conv 75% EU) - P05','SOS540','Irregularity','NECS'),
	 ('Late Change  (EAFRD Non Conv 75% EU) - P06','SOS541','Irregularity','NECS'),
	 ('Non Declaration of Land  (EAFRD Non Conv 75% EU) - P08','SOS542','Irregularity','NECS'),
	 ('Cross Compliance  (EAFRD Non Conv 75% EU) - P14','SOS543','Irregularity','NECS'),
	 ('RD Refusals  (EAFRD Non Conv 75% EU) - P22','SOS544','Irregularity','NECS'),
	 ('RD Withdrawals  (EAFRD Non Conv 75% EU) - P23','SOS545','Irregularity','NECS'),
	 ('Over Declaration  (EAFRD Conv 85% EU) - P02','SOS546','Irregularity','NECS'),
	 ('Late Claim Submission  (EAFRD Conv 85% EU) - P05','SOS547','Irregularity','NECS'),
	 ('Late Change  (EAFRD Conv 85% EU) - P06','SOS548','Irregularity','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Non Declaration of Land  (EAFRD Conv 85% EU) - P08','SOS549','Irregularity','NECS'),
	 ('Cross Compliance  (EAFRD Conv 85% EU) - P14','SOS550','Irregularity','NECS'),
	 ('RD Refusals  (EAFRD Conv 85% EU) - P22','SOS551','Irregularity','NECS'),
	 ('RD Withdrawals  (EAFRD Conv 85% EU) - P23','SOS552','Irregularity','NECS'),
	 ('State Aid Over Declaration  - P02','SOS553','Exchequer','NECS'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS554','Exchequer','NECS'),
	 ('Late Claim Submission  (State Aid Revenue) - P05','SOS555','Exchequer','NECS'),
	 ('Late Change  (State Aid Revenue) - P06','SOS556','Exchequer','NECS'),
	 ('Non Declaration of Land  (State Aid Revenue) - P08','SOS557','Exchequer','NECS'),
	 ('Cross Compliance  (State Aid Revenue) - P14','SOS558','Exchequer','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('RD Refusals  (State Aid Revenue) - P22','SOS559','Exchequer','NECS'),
	 ('RD Withdrawals  (State Aid Revenue) - P23','SOS560','Exchequer','NECS'),
	 ('Over Declaration  (P1 to P2 Capital) - P02','SOS570','Admin Error','NECS'),
	 ('Over Declaration Reduction (P1 to P2 Capital) - P24','SOS571','Admin Error','NECS'),
	 ('Over Declaration  (P1 to P2 Revenue) - P02','SOS572','Admin Error','NECS'),
	 ('Late Claim Submission  (P1 to P2 Revenue) - P05','SOS573','Admin Error','NECS'),
	 ('Late Change  (P1 to P2 Revenue) - P06','SOS574','Admin Error','NECS'),
	 ('Non Declaration of Land  (P1 to P2 Revenue) - P08','SOS575','Admin Error','NECS'),
	 ('Cross Compliance  (P1 to P2 Revenue) - P14','SOS576','Admin Error','NECS'),
	 ('RD Refusals  (P1 to P2 Revenue) - P22','SOS577','Admin Error','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('RD Withdrawals  (P1 to P2 Revenue) - P23','SOS578','Admin Error','NECS'),
	 ('Over Declaration  (EAFRD Non Conv 75% EU) - P02','SOS579','Admin Error','NECS'),
	 ('Late Claim Submission  (EAFRD Non Conv 75% EU) - P05','SOS580','Admin Error','NECS'),
	 ('Late Change  (EAFRD Non Conv 75% EU) - P06','SOS581','Admin Error','NECS'),
	 ('Non Declaration of Land  (EAFRD Non Conv 75% EU) - P08','SOS582','Admin Error','NECS'),
	 ('Cross Compliance  (EAFRD Non Conv 75% EU) - P14','SOS583','Admin Error','NECS'),
	 ('RD Refusals  (EAFRD Non Conv 75% EU) - P22','SOS584','Admin Error','NECS'),
	 ('RD Withdrawals  (EAFRD Non Conv 75% EU) - P23','SOS585','Admin Error','NECS'),
	 ('Over Declaration  (EAFRD Conv 85% EU) - P02','SOS586','Admin Error','NECS'),
	 ('Late Claim Submission  (EAFRD Conv 85% EU) - P05','SOS587','Admin Error','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Late Change  (EAFRD Conv 85% EU) - P06','SOS588','Admin Error','NECS'),
	 ('Non Declaration of Land  (EAFRD Conv 85% EU) - P08','SOS589','Admin Error','NECS'),
	 ('Cross Compliance  (EAFRD Conv 85% EU) - P14','SOS590','Admin Error','NECS'),
	 ('RD Refusals  (EAFRD Conv 85% EU) - P22','SOS591','Admin Error','NECS'),
	 ('RD Withdrawals  (EAFRD Conv 85% EU) - P23','SOS592','Admin Error','NECS'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) - P24','SOS561','Irregularity','NECS'),
	 ('Over Declaration Reduction (EAFRD Non Conv 75% EU) - P24','SOS562','Irregularity','NECS'),
	 ('Over Declaration Reduction (EAFRD Conv 85% EU) - P24','SOS563','Irregularity','NECS'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) - P24','SOS593','Admin Error','NECS'),
	 ('Over Declaration Reduction (EAFRD Non Conv 75% EU) - P24','SOS594','Admin Error','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Over Declaration Reduction (EAFRD Conv 85% EU) - P24','SOS595','Admin Error','NECS'),
	 ('P1 to P2 Transfer','SOS393','Penalty','NECS'),
	 ('P1 to P2 Transfer - Axis 2','SOS388','Admin Error','NECS'),
	 ('Exchequer Recoveries','SOS355','Exchequer','NECS'),
	 ('CS Revenue - Over Declaration Penalty (P1 to P2)','SOS532','Irregularity','NECS'),
	 ('State Aid Recovery','SOS352','Exchequer','NECS'),
	 ('Exchequer Recoveries','SOS355','Exchequer','NECS'),
	 ('Over Declaration Penalty','SOS553','Exchequer','NECS'),
	 ('Over Declaration Reduction','SOS554','Exchequer','NECS'),
	 ('Late claim submission penalty','SOS555','Exchequer','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('late change penalty','SOS556','Exchequer','NECS'),
	 ('Non declaration of land penalty','SOS557','Exchequer','NECS'),
	 ('Cross compliance penalty','SOS558','Exchequer','NECS'),
	 ('Rural Development refusals','SOS559','Exchequer','NECS'),
	 ('Rural Development withdrawals','SOS560','Exchequer','NECS'),
	 ('Admin error - (DRD)','SOS750','Admin Error','NECS'),
	 ('Irregularity - (DRD)','SOS770','Irregularity','NECS'),
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS940','Admin Error','NECS'),
	 ('CS Revenue - Late claim submission penalty (DRD)','SOS941','Admin Error','NECS'),
	 ('CS Revenue - Late change penalty (DRD)','SOS942','Admin Error','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Revenue - Non decl of land penalty (DRD)','SOS943','Admin Error','NECS'),
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS944','Admin Error','NECS'),
	 ('CS Revenue-Rural Development refusals (DRD)','SOS945','Admin Error','NECS'),
	 ('CS Revenue - Rural Development withdrawals (DRD)','SOS946','Admin Error','NECS'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS947','Admin Error','NECS'),
	 ('CS Revenue - Over Declaration Penalty (DRD))','SOS948','Admin Error','NECS'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS949','Admin Error','NECS'),
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS960','Irregularity','NECS'),
	 ('CS Revenue - Late claim sub penalty (DRD)','SOS961','Irregularity','NECS'),
	 ('CS Revenue - Late change penalty (DRD)','SOS962','Irregularity','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Revenue - Non decl of land penalty (DRD)','SOS963','Irregularity','NECS'),
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS964','Irregularity','NECS'),
	 ('CS Revenue - Rural Development refusals (DRD)','SOS965','Irregularity','NECS'),
	 ('CS Revenue - Rural Development withrls (DRD)','SOS966','Irregularity','NECS'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS967','Irregularity','NECS'),
	 ('CS Revenue - Over Declaration Penalty (DRD)','SOS968','Irregularity','NECS'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS969','Irregularity','NECS'),
	 ('State Aid Recovery','SOS352','Exchequer','NE-LS'),
	 ('Exchequer Recoveries','SOS355','Exchequer','NE-LS'),
	 ('Over Declaration Penalty','SOS553','Exchequer','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('Over Declaration Reduction','SOS554','Exchequer','NE-LS'),
	 ('Late claim submission penalty','SOS555','Exchequer','NE-LS'),
	 ('late change penalty','SOS556','Exchequer','NE-LS'),
	 ('Non declaration of land penalty','SOS557','Exchequer','NE-LS'),
	 ('Cross compliance penalty','SOS558','Exchequer','NE-LS'),
	 ('Rural Development refusals','SOS559','Exchequer','NE-LS'),
	 ('Rural Development withdrawals','SOS560','Exchequer','NE-LS'),
	 ('Admin error - (DRD)','SOS750','Admin','NE-LS'),
	 ('Irregularity - (DRD)','SOS770','Irregularity','NE-LS'),
	 ('Penalties - (DRD)','SOS780','Penalty','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS940','Admin','NE-LS'),
	 ('CS Revenue - Late claim submission penalty (DRD)','SOS941','Admin','NE-LS'),
	 ('CS Revenue - Late change penalty (DRD)','SOS942','Admin','NE-LS'),
	 ('CS Revenue - Non decl of land penalty (DRD)','SOS943','Admin','NE-LS'),
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS944','Admin','NE-LS'),
	 ('CS Revenue-Rural Development refusals (DRD)','SOS945','Admin','NE-LS'),
	 ('CS Revenue - Rural Development withdrawals (DRD)','SOS946','Admin','NE-LS'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS947','Admin','NE-LS'),
	 ('CS Revenue - Over Declaration Penalty (DRD))','SOS948','Admin','NE-LS'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS949','Admin','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS960','Irregularity','NE-LS'),
	 ('CS Revenue - Late claim sub penalty (DRD)','SOS961','Irregularity','NE-LS'),
	 ('CS Revenue - Late change penalty (DRD)','SOS962','Irregularity','NE-LS'),
	 ('CS Revenue - Non decl of land penalty (DRD)','SOS963','Irregularity','NE-LS'),
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS964','Irregularity','NE-LS'),
	 ('CS Revenue - Rural Development refusals (DRD)','SOS965','Irregularity','NE-LS'),
	 ('CS Revenue - Rural Development withrls (DRD)','SOS966','Irregularity','NE-LS'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS967','Irregularity','NE-LS'),
	 ('CS Revenue - Over Declaration Penalty (DRD)','SOS968','Irregularity','NE-LS'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS969','Irregularity','NE-LS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('P1 to P2 Transfer','SOS383','Irregularity','EA'),
	 ('P1 to P2 Transfer','SOS388','Admin Error','EA'),
	 ('Admin Error – (DRD)','SOS750','Admin Error','EACS'),
	 ('Irregularity - (DRD)','SOS770','Irregularity','EACS'),
	 ('Irregularity - (DRD)','SOS770','Irregularity','FC'),
	 ('Admin error - (DRD)','SOS750','Admin Error','FC'),
	 ('State Aid Recovery','SOS352','Exchequer','FC'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS969','Irregularity','FC'),
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS960','Irregularity','FC'),
	 ('CS Revenue - Late claim sub penalty (DRD)','SOS961','Irregularity','FC');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS964','Irregularity','FC'),
	 ('CS Revenue - Rural Development refusals (DRD)','SOS965','Irregularity','FC'),
	 ('Over Declaration Penalty','SOS553','Exchequer','FC'),
	 ('Over Declaration Reduction','SOS554','Exchequer','FC'),
	 ('Late claim submission penalty','SOS555','Exchequer','FC'),
	 ('Cross compliance penalty','SOS558','Exchequer','FC'),
	 ('CS Capital - Over Declaration Penalty - (DRD)','SOS949','Admin Error','FC'),
	 ('CS Capital - Over Declaration Reduction - (DRD)','SOS940','Admin Error','FC'),
	 ('CS Revenue - Over Declaration Penalty (DRD))','SOS948','Admin Error','FC'),
	 ('CS Revenue - Late claim submission penalty (DRD)','SOS941','Admin Error','FC');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ar (description,code,"type",org) VALUES
	 ('CS Revenue - Cross compliance penalty (DRD)','SOS944','Admin Error','FC'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS967','Irregularity','FC'),
	 ('CS Revenue - Over Declaration Reduction (DRD)','SOS947','Admin Error','FC'),
	 ('Farming Equipment Technology Fund','SOS330','Admin Error','RDT Domestic');
