INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Interceptions Clearing Repayment ','SCC760','DA, DF'),
	 ('R00 Crisis reserve distribution','SOS216','DA'),
	 ('P15 FDM Budget Adjustment','SOS260','DA'),
	 ('P12 Crisis reserve reduction','SOS266','DA'),
	 ('P14 Cross compliance penalty','SOS350','DA'),
	 ('P03 Non-compliance penalty','SOS351','DA'),
	 ('P08 Non declaration of land penalty','SOS361','DA'),
	 ('P02 - Over declaration penalty','SOS362','DA'),
	 ('P04 Administrative penalty','SOS363','DA'),
	 ('P11 Reduction due to Net Ceiling Scaleback','SOS364','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('P05 Late claim submission penalty','SOS367','DA'),
	 ('P06 Late change penalty','SOS368','DA'),
	 ('P07 Late claim for entitlement NR penalty','SOS369','DA'),
	 ('P09 Linear reduction supplement','SOS400','DA'),
	 ('P10 Breach of Ceiling LR penalty','SOS402','DA'),
	 ('P01 - Young Farmer false evidence penalty','SOS404','DA'),
	 ('P13 5% reduction over â‚¬150,000','SOS410','DA'),
	 ('P16 15% reduction over â‚¬150,000','SOS415','DA'),
	 ('P17 30% reduction over â‚¬200,000','SOS416','DA'),
	 ('P18 55% reduction over â‚¬250,000','SOS417','DA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('P19 100% reduction over â‚¬150,000','SOS420','DA'),
	 ('P20 100% reduction over â‚¬300,000','SOS420','DA'),
	 ('P21 100% reduction over â‚¬600,000','SOS420','DA'),
	 ('BPS Progressive Red Band 1','SOS471','DA'),
	 ('BPS Progressive Red Band 2','SOS472','DA'),
	 ('BPS Progressive Red Band 3','SOS473','DA'),
	 ('BPS Progressive Red Band 4','SOS474','DA'),
	 ('SFI Management Payment','SOS710','DA'),
	 ('DRD - Over Dec Red','SOS927','DA'),
	 ('Interceptions Clearing Repayment ','SCC760','IP');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('EX0 - Interim Payment','SOS235','IP'),
	 ('Ex Gratia Interest payment','SOS245','XG'),
	 ('Ex Gratia Payment','SOS240','XG'),
	 ('Interceptions Clearing Repayment ','SCC760','BK, XG'),
	 ('Defra reimbursement','SOO930','BK'),
	 ('National Modulation','SOM610','SPS'),
	 ('Three Year Penalty','SOS365','SPS'),
	 ('EC Modulation','SOM615','SPS'),
	 ('G00 - Gross Value of Claim','SOS210','SPS'),
	 ('Advance Payment','SOS211','SPS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Additional Payments','SOS215','SPS'),
	 ('R00 Crisis reserve distribution','SOS216','SPS'),
	 ('P15 FDM Budget Adjustment','SOS260','SPS'),
	 ('Other Penalty (FDM)','SOS263','SPS'),
	 ('Late payment penalty (FDM)','SOS264','SPS'),
	 ('Non Declaration Penalty (FDM)','SOS265','SPS'),
	 ('P12 Crisis reserve reduction','SOS266','SPS'),
	 ('P14 Cross compliance penalty','SOS350','SPS'),
	 ('P08 Non declaration of land penalty','SOS361','SPS'),
	 ('Interceptions Clearing Repayment ','SCC760','SPS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('G00 - GROSS VALUE OF CLAIM','SOS210','TR'),
	 ('Top-up Payment','SOS213','TR'),
	 ('State Aid Top-up','SOS228','TR'),
	 ('State Aid Standalone','SOS229','TR'),
	 ('EX0 - Interim Payment','SOS355','TR'),
	 ('Interceptions Clearing Repayment ','SCC760','OPA, TR'),
	 ('OPA Funding','SOF810','OPA'),
	 ('OPA Interest Recoveries','SOF822','OPA'),
	 ('Receipts from OPA','SOF825','OPA'),
	 ('OPA Over / Under Funding','SOF830','OPA');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('National modulation payable to OPA','SOM678','OPA'),
	 ('EC modulation payable to OPA','SOM682','OPA'),
	 ('European Commission Funding - OPA claim','SRR850','OPA'),
	 ('Non-CAP Payment','SOS230','FCLS'),
	 ('State Aid Standalone','SOS229','FCLS'),
	 ('DRD Payment','SOS710','FCLS'),
	 ('State Aid Top-up','SOS228','FCCS'),
	 ('State Aid Standalone','SOS229','FCCS'),
	 ('State Aid Over Declaration Penalty - P02','SOS231','FCCS'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS232','FCCS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Late Claim Submission Penalty (State Aid Revenue) - P05','SOS233','FCCS'),
	 ('Cross Compliance Penalty (State Aid Revenue) - P14','SOS236','FCCS'),
	 ('DRD Payment','SOS710','FCCS'),
	 ('DRD AP CS Cap. Over Dec Red.','SOS920','FCCS'),
	 ('DRD AP CS Rev - Late claim sub penalty ','SOS921','FCCS'),
	 ('DRD AP CS Rev - Cross compliance penalty','SOS924','FCCS'),
	 ('DRD AP CS Rev - Over declar Reduction','SOS927','FCCS'),
	 ('Over Declaration Penalty (DRD)','SOS928','FCCS'),
	 ('DRD AP CS Cap. Over Dec Pen.','SOS929','FCCS'),
	 ('State Aid Standalone','SOS229','RDPE');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('DRD Payment','SOS710','RDPE'),
	 ('P1 to P2 Transfer - 100% EU','SOS273','RDT'),
	 ('State Aid Standalone','SOS229','RDT'),
	 ('DRD Payment','SOS710','RDT'),
	 ('Normal Payment','SOS210','HE'),
	 ('State Aid Top-up','SOS228','NE'),
	 ('State Aid Standalone','SOS229','NE'),
	 ('State Aid Over Declaration Penalty - P02','SOS231','NE'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS232','NE'),
	 ('Late Claim Submission Penalty (State Aid Revenue) - P05','SOS233','NE');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Late Change Penalty (State Aid Revenue) - P06','SOS234','NE'),
	 ('Cross Compliance Penalty (State Aid Revenue) - P14','SOS236','NE'),
	 ('RD Refusals Penalty (State Aid Revenue) - P22','SOS237','NE'),
	 ('RD Withdrawals Penalty (State Aid Revenue) - P23','SOS238','NE'),
	 ('Non Declaration of Land Penalty (State Aid Revenue) - P08','SOS239','NE'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) â€“ P24','SOS523','NE'),
	 ('DRD Payment','SOS710','NE'),
	 ('DRD AP CS Cap. Over Dec Red.','SOS920','NE'),
	 ('DRD AP CS Rev - Late claim sub penalty ','SOS921','NE'),
	 ('DRD AP CS Rev - Late change penalty','SOS922','NE');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('DRD AP CS Rev - Non declar of land penalty','SOS923','NE'),
	 ('DRD AP CS Rev - Cross compliance penalty','SOS924','NE'),
	 ('DRD AP CS Rev - Rural Devel refusals ','SOS925','NE'),
	 ('G00 - GROSS VALUE OF CLAIM','SOS210','DA,DF'),
	 ('DRD AP CS Rev - Rural Devel withdrawals','SOS926','NE'),
	 ('DRD AP CS Rev - Over declar Reduction','SOS927','NE'),
	 ('Over Declaration Penalty (DRD)','SOS928','NE'),
	 ('DRD AP CS Cap. Over Dec Pen.','SOS929','NE'),
	 ('State Aid Top-up','SOS228','NELS'),
	 ('State Aid Standalone','SOS229','NELS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Core EAFRD - non Conv - 75% EU','SOS270','NELS'),
	 ('Core EAFRD - Conv 85% EU - 85% EU','SOS271','NELS'),
	 ('P1 to P2 Transfer - 100% EU','SOS273','NELS'),
	 ('State Aid Top-up','SOS228','NEP1'),
	 ('State Aid Standalone','SOS229','NEP1'),
	 ('State Aid Over Declaration Penalty - P02','SOS231','NEP1'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS232','NEP1'),
	 ('Late Claim Submission Penalty (State Aid Revenue) - P05','SOS233','NEP1'),
	 ('Late Change Penalty (State Aid Revenue) - P06','SOS234','NEP1'),
	 ('Cross Compliance Penalty (State Aid Revenue) - P14','SOS236','NEP1');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('RD Refusals Penalty (State Aid Revenue) - P22','SOS237','NEP1'),
	 ('RD Withdrawals Penalty (State Aid Revenue) - P23','SOS238','NEP1'),
	 ('Non Declaration of Land Penalty (State Aid Revenue) - P08','SOS239','NEP1'),
	 ('DRD Payment','SOS710','NEP1'),
	 ('DRD AP CS Cap. Over Dec Red.','SOS920','NEP1'),
	 ('DRD AP CS Rev - Late claim sub penalty ','SOS921','NEP1'),
	 ('DRD AP CS Rev - Late change penalty','SOS922','NEP1'),
	 ('DRD AP CS Rev - Non declar of land penalty','SOS923','NEP1'),
	 ('DRD AP CS Rev - Cross compliance penalty','SOS924','NEP1'),
	 ('DRD AP CS Rev - Rural Devel refusals ','SOS925','NEP1');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('DRD AP CS Rev - Rural Devel withdrawals','SOS926','NEP1'),
	 ('DRD AP CS Rev - Over declar Reduction','SOS927','NEP1'),
	 ('Over Declaration Penalty (DRD)','SOS928','NEP1'),
	 ('DRD AP CS Cap. Over Dec Pen.','SOS929','NEP1'),
	 ('DRD Payment','SOS710','EA'),
	 ('State Aid Top-up','SOS228','NECS'),
	 ('State Aid Standalone','SOS229','NECS'),
	 ('State Aid Over Declaration Penalty - P02','SOS231','NECS'),
	 ('State Aid Over Declaration Reduction (Capital only) - P24','SOS232','NECS'),
	 ('Late Claim Submission Penalty (State Aid Revenue) - P05','SOS233','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Late Change Penalty (State Aid Revenue) - P06','SOS234','NECS'),
	 ('Cross Compliance Penalty (State Aid Revenue) - P14','SOS236','NECS'),
	 ('RD Refusals Penalty (State Aid Revenue) - P22','SOS237','NECS'),
	 ('RD Withdrawals Penalty (State Aid Revenue) - P23','SOS238','NECS'),
	 ('Non Declaration of Land Penalty (State Aid Revenue) - P08','SOS239','NECS'),
	 ('Over Declaration Reduction (P1 to P2 Revenue) â€“ P24','SOS523','NECS'),
	 ('DRD Payment','SOS710','NECS'),
	 ('DRD AP CS Cap. Over Dec Red.','SOS920','NECS'),
	 ('DRD AP CS Rev - Late claim sub penalty ','SOS921','NECS'),
	 ('DRD AP CS Rev - Late change penalty','SOS922','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('DRD AP CS Rev - Non declar of land penalty','SOS923','NECS'),
	 ('DRD AP CS Rev - Cross compliance penalty','SOS924','NECS'),
	 ('DRD AP CS Rev - Rural Devel refusals ','SOS925','NECS'),
	 ('DRD AP CS Rev - Rural Devel withdrawals','SOS926','NECS'),
	 ('DRD AP CS Rev - Over declar Reduction','SOS927','NECS'),
	 ('Over Declaration Penalty (DRD)','SOS928','NECS'),
	 ('DRD AP CS Cap. Over Dec Pen.','SOS929','NECS'),
	 ('Core EAFRD - non Conv - 75% EU','SOS270','NECS'),
	 ('Core EAFRD - Conv 85% EU - 85% EU','SOS271','NECS'),
	 ('P1 to P2 Transfer - 100% EU','SOS273','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Over Declaration (P1 to P2 Revenue) - P02','SOS502','NECS'),
	 ('Late Claim Submission (P1 to P2 Revenue) - P05','SOS503','NECS'),
	 ('Late Change (P1 to P2 Revenue) - P06','SOS504','NECS'),
	 ('Non Declaration of Land (P1 to P2 Revenue) - P08','SOS505','NECS'),
	 ('Cross Compliance (P1 to P2 Revenue) - P14','SOS506','NECS'),
	 ('RD Refusals (P1 to P2 Revenue) - P22','SOS507','NECS'),
	 ('RD Withdrawals (P1 to P2 Revenue) - P23','SOS508','NECS'),
	 ('Over Declaration (EAFRD Non Conv 75% EU) - P02','SOS509','NECS'),
	 ('Late Claim Submission (EAFRD Non Conv 75% EU) - P05','SOS510','NECS'),
	 ('Late Change (EAFRD Non Conv 75% EU) - P06','SOS511','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('Non Declaration of Land (EAFRD Non Conv 75% EU) - P08','SOS512','NECS'),
	 ('Cross Compliance (EAFRD Non Conv 75% EU) - P14','SOS513','NECS'),
	 ('RD Refusals (EAFRD Non Conv 75% EU) - P22','SOS514','NECS'),
	 ('RD Withdrawals (EAFRD Non Conv 75% EU) - P23','SOS515','NECS'),
	 ('Over Declaration (EAFRD Conv 85% EU) - P02','SOS516','NECS'),
	 ('Late Claim Submission (EAFRD Conv 85% EU) - P05','SOS517','NECS'),
	 ('Late Change (EAFRD Conv 85% EU) - P06','SOS518','NECS'),
	 ('Non Declaration of Land (EAFRD Conv 85% EU) - P08','SOS519','NECS'),
	 ('Cross Compliance (EAFRD Conv 85% EU) - P14','SOS520','NECS'),
	 ('RD Refusals (EAFRD Conv 85% EU) - P22','SOS521','NECS');
INSERT INTO rpa_mit_invoices.public.lookup_accounts_ap (description,code,org) VALUES
	 ('RD Withdrawals (EAFRD Conv 85% EU) - P23','SOS522','NECS'),
	 ('Over Declaration Reduction (EAFRD Non Conv 75% EU) - P24','SOS524','NECS'),
	 ('Over Declaration Reduction (EAFRD Conv 85% EU) - P24','SOS525','NECS');
