INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RP00','RPA','England'),
	 ('RP01','RPA','Scotland'),
	 ('RP02','RPA','Wales'),
	 ('RP03','RPA','N Ireland'),
	 ('OP01','OPA','RPA SG Funding'),
	 ('OP02','OPA','RPA WG Funding'),
	 ('OP03','OPA','RPA DARDNI Funding'),
	 ('OP04','OPA','RPA FC Funding - Scotland'),
	 ('OP05','OPA','RPA Other Funding'),
	 ('RP00','TR','England');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RP01','TR','Scotland'),
	 ('RP02','TR','Wales'),
	 ('RP03','TR','N Ireland'),
	 ('DE00','TR','RDPE (Defra)'),
	 ('DE00','RDPE','RDPE (Defra)'),
	 ('DE10','RDPE','RDPE (Defra CSF)'),
	 ('FC00','FC','FC'),
	 ('FC99','FC','FC-MP'),
	 ('RP99','NE','RPA'),
	 ('NE99','NE','NE-MP');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('FC99','FC','FC-MP'),
	 ('GR00','RDT','Grants Regulations'),
	 ('RC01','RDT','RDD - CP'),
	 ('RC02','RDT','RDD - CP'),
	 ('RC03','RDT','RDD - CP'),
	 ('RC04','RDT','RDD - CP'),
	 ('RC05','RDT','RDD - CP'),
	 ('RC06','RDT','RDD - CP'),
	 ('RC07','RDT','RDD - CP'),
	 ('RC08','RDT','RDD - CP');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RC09','RDT','RDD - CP'),
	 ('RC10','RDT','RDD - CP'),
	 ('RC11','RDT','RDD - FRF'),
	 ('RD00','RDT','RDT'),
	 ('RD01','RDT','RDD - LEADER'),
	 ('RD02','RDT','RDD - LEADER'),
	 ('RD03','RDT','RDD - LEADER'),
	 ('RD04','RDT','RDD - LEADER'),
	 ('RD05','RDT','RDD - LEADER'),
	 ('RD06','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD07','RDT','RDD - LEADER'),
	 ('RD08','RDT','RDD - LEADER'),
	 ('RD09','RDT','RDD - LEADER'),
	 ('RD10','RDT','RDD - LEADER'),
	 ('RD11','RDT','RDD - LEADER'),
	 ('RD12','RDT','RDD - LEADER'),
	 ('RD13','RDT','RDD - LEADER'),
	 ('RD14','RDT','RDD - LEADER'),
	 ('RD15','RDT','RDD - LEADER'),
	 ('RD16','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD17','RDT','RDD - LEADER'),
	 ('RD18','RDT','RDD - LEADER'),
	 ('RD19','RDT','RDD - LEADER'),
	 ('RD20','RDT','RDD - LEADER'),
	 ('RD21','RDT','RDD - LEADER'),
	 ('RD22','RDT','RDD - LEADER'),
	 ('RD23','RDT','RDD - LEADER'),
	 ('RD24','RDT','RDD - LEADER'),
	 ('RD25','RDT','RDD - LEADER'),
	 ('RD26','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD27','RDT','RDD - LEADER'),
	 ('RD28','RDT','RDD - LEADER'),
	 ('RD29','RDT','RDD - LEADER'),
	 ('RD30','RDT','RDD - LEADER'),
	 ('RD31','RDT','RDD - LEADER'),
	 ('RD32','RDT','RDD - LEADER'),
	 ('RD33','RDT','RDD - LEADER'),
	 ('RD34','RDT','RDD - LEADER'),
	 ('RD35','RDT','RDD - LEADER'),
	 ('RD36','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD37','RDT','RDD - LEADER'),
	 ('RD38','RDT','RDD - LEADER'),
	 ('RD39','RDT','RDD - LEADER'),
	 ('RD40','RDT','RDD - LEADER'),
	 ('RD41','RDT','RDD - LEADER'),
	 ('RD42','RDT','RDD - LEADER'),
	 ('RD43','RDT','RDD - LEADER'),
	 ('RD44','RDT','RDD - LEADER'),
	 ('RD45','RDT','RDD - LEADER'),
	 ('RD46','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD47','RDT','RDD - LEADER'),
	 ('RD48','RDT','RDD - LEADER'),
	 ('RD49','RDT','RDD - LEADER'),
	 ('RD50','RDT','RDD - LEADER'),
	 ('RD51','RDT','RDD - LEADER'),
	 ('RD52','RDT','RDD - LEADER'),
	 ('RD53','RDT','RDD - LEADER'),
	 ('RD54','RDT','RDD - LEADER'),
	 ('RD55','RDT','RDD - LEADER'),
	 ('RD56','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD57','RDT','RDD - LEADER'),
	 ('RD58','RDT','RDD - LEADER'),
	 ('RD59','RDT','RDD - LEADER'),
	 ('RD60','RDT','RDD - LEADER'),
	 ('RD61','RDT','RDD - LEADER'),
	 ('RD62','RDT','RDD - LEADER'),
	 ('RD63','RDT','RDD - LEADER'),
	 ('RD64','RDT','RDD - LEADER'),
	 ('RD65','RDT','RDD - LEADER'),
	 ('RD66','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD67','RDT','RDD - LEADER'),
	 ('RD68','RDT','RDD - LEADER'),
	 ('RD69','RDT','RDD - LEADER'),
	 ('RD70','RDT','RDD - LEADER'),
	 ('RD71','RDT','RDD - LEADER'),
	 ('RD72','RDT','RDD - LEADER'),
	 ('RD73','RDT','RDD - LEADER'),
	 ('RD74','RDT','RDD - LEADER'),
	 ('RD75','RDT','RDD - LEADER'),
	 ('RD76','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RD77','RDT','RDD - LEADER'),
	 ('RD78','RDT','RDD - LEADER'),
	 ('RD79','RDT','RDD - LEADER'),
	 ('RD80','RDT','RDD - LEADER'),
	 ('RG01','RDT','RDD - GROWTH'),
	 ('RG02','RDT','RDD - GROWTH'),
	 ('RG03','RDT','RDD - GROWTH'),
	 ('RG04','RDT','RDD - GROWTH'),
	 ('RG05','RDT','RDD - GROWTH'),
	 ('RG06','RDT','RDD - GROWTH');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RG07','RDT','RDD - GROWTH'),
	 ('RG08','RDT','RDD - GROWTH'),
	 ('RG09','RDT','RDD - GROWTH'),
	 ('RG10','RDT','RDD - GROWTH'),
	 ('RG11','RDT','RDD - GROWTH'),
	 ('RG12','RDT','RDD - GROWTH'),
	 ('RG13','RDT','RDD - GROWTH'),
	 ('RG14','RDT','RDD - GROWTH'),
	 ('RG15','RDT','RDD - GROWTH'),
	 ('RG16','RDT','RDD - GROWTH');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RG17','RDT','RDD - GROWTH'),
	 ('RG18','RDT','RDD - GROWTH'),
	 ('RG19','RDT','RDD - GROWTH'),
	 ('RG20','RDT','RDD - GROWTH'),
	 ('RG21','RDT','RDD - GROWTH'),
	 ('RG22','RDT','RDD - GROWTH'),
	 ('RG23','RDT','RDD - GROWTH'),
	 ('RG24','RDT','RDD - GROWTH'),
	 ('RG25','RDT','RDD - GROWTH'),
	 ('RG26','RDT','RDD - GROWTH');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RG27','RDT','RDD - GROWTH'),
	 ('RG28','RDT','RDD - GROWTH'),
	 ('RG29','RDT','RDD - GROWTH'),
	 ('RG30','RDT','RDD - GROWTH'),
	 ('RG31','RDT','RDD - GROWTH'),
	 ('RG32','RDT','RDD - GROWTH'),
	 ('RG33','RDT','RDD - GROWTH'),
	 ('RG34','RDT','RDD - GROWTH'),
	 ('RG35','RDT','RDD - GROWTH'),
	 ('RG36','RDT','RDD - GROWTH');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RG37','RDT','RDD - GROWTH'),
	 ('RL01','RDT','RDD - LEADER'),
	 ('RL02','RDT','RDD - LEADER'),
	 ('RL03','RDT','RDD - LEADER'),
	 ('RL04','RDT','RDD - LEADER'),
	 ('RL05','RDT','RDD - LEADER'),
	 ('RL06','RDT','RDD - LEADER'),
	 ('RL07','RDT','RDD - LEADER'),
	 ('RL08','RDT','RDD - LEADER'),
	 ('RL09','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL10','RDT','RDD - LEADER'),
	 ('RL11','RDT','RDD - LEADER'),
	 ('RL12','RDT','RDD - LEADER'),
	 ('RL13','RDT','RDD - LEADER'),
	 ('RL14','RDT','RDD - LEADER'),
	 ('RL15','RDT','RDD - LEADER'),
	 ('RL16','RDT','RDD - LEADER'),
	 ('RL17','RDT','RDD - LEADER'),
	 ('RL18','RDT','RDD - LEADER'),
	 ('RL19','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL20','RDT','RDD - LEADER'),
	 ('RL21','RDT','RDD - LEADER'),
	 ('RL22','RDT','RDD - LEADER'),
	 ('RL23','RDT','RDD - LEADER'),
	 ('RL24','RDT','RDD - LEADER'),
	 ('RL25','RDT','RDD - LEADER'),
	 ('RL26','RDT','RDD - LEADER'),
	 ('RL27','RDT','RDD - LEADER'),
	 ('RL28','RDT','RDD - LEADER'),
	 ('RL29','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL30','RDT','RDD - LEADER'),
	 ('RL31','RDT','RDD - LEADER'),
	 ('RL32','RDT','RDD - LEADER'),
	 ('RL33','RDT','RDD - LEADER'),
	 ('RL34','RDT','RDD - LEADER'),
	 ('RL35','RDT','RDD - LEADER'),
	 ('RL36','RDT','RDD - LEADER'),
	 ('RL37','RDT','RDD - LEADER'),
	 ('RL38','RDT','RDD - LEADER'),
	 ('RL39','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL40','RDT','RDD - LEADER'),
	 ('RL41','RDT','RDD - LEADER'),
	 ('RL42','RDT','RDD - LEADER'),
	 ('RL43','RDT','RDD - LEADER'),
	 ('RL44','RDT','RDD - LEADER'),
	 ('RL45','RDT','RDD - LEADER'),
	 ('RL46','RDT','RDD - LEADER'),
	 ('RL47','RDT','RDD - LEADER'),
	 ('RL48','RDT','RDD - LEADER'),
	 ('RL49','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL50','RDT','RDD - LEADER'),
	 ('RL51','RDT','RDD - LEADER'),
	 ('RL52','RDT','RDD - LEADER'),
	 ('RL53','RDT','RDD - LEADER'),
	 ('RL54','RDT','RDD - LEADER'),
	 ('RL55','RDT','RDD - LEADER'),
	 ('RL56','RDT','RDD - LEADER'),
	 ('RL57','RDT','RDD - LEADER'),
	 ('RL58','RDT','RDD - LEADER'),
	 ('RL59','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL60','RDT','RDD - LEADER'),
	 ('RL61','RDT','RDD - LEADER'),
	 ('RL62','RDT','RDD - LEADER'),
	 ('RL63','RDT','RDD - LEADER'),
	 ('RL64','RDT','RDD - LEADER'),
	 ('RL65','RDT','RDD - LEADER'),
	 ('RL66','RDT','RDD - LEADER'),
	 ('RL67','RDT','RDD - LEADER'),
	 ('RL68','RDT','RDD - LEADER'),
	 ('RL69','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL70','RDT','RDD - LEADER'),
	 ('RL71','RDT','RDD - LEADER'),
	 ('RL72','RDT','RDD - LEADER'),
	 ('RL73','RDT','RDD - LEADER'),
	 ('RL74','RDT','RDD - LEADER'),
	 ('RL75','RDT','RDD - LEADER'),
	 ('RL76','RDT','RDD - LEADER'),
	 ('RL77','RDT','RDD - LEADER'),
	 ('RL78','RDT','RDD - LEADER'),
	 ('RL79','RDT','RDD - LEADER');
INSERT INTO rpa_mit_invoices.public.lookup_deliverybodycodes (code,org,description) VALUES
	 ('RL80','RDT','RDD - LEADER'),
	 ('EA00','EA','Environment Agency');
