INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('ï»¿Retrospective commons (UTP)','10323','XG'),
	 ('Retrospective commons (HFA) ','10322','XG'),
	 ('Retrospective Commons ','10320','XG'),
	 ('Milk Production Reduction','10267','XG'),
	 ('Sugar levy reimbursements','10313','XG'),
	 ('SPS Scheme','10301','XG'),
	 ('No Scheme Analysis','0','XG'),
	 ('BPS','10501','XG'),
	 ('XL Bully Compensation Scheme','17101','HE'),
	 ('Vet Visits - Sheep','18001','HE');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Vet Visits - Beef','18002','HE'),
	 ('Vet Visits - Dairy','18003','HE'),
	 ('Vet Visits - Pigs','18004','HE'),
	 ('FDM Reimbursement - 2020','10580','DA'),
	 ('BPS','10501','DA'),
	 ('Greening','10511','DA'),
	 ('Young Farmer','10521','DA'),
	 ('Redistributive Payment (Wales)','10531','DA'),
	 ('FDM Reimbursement','10575','DA'),
	 ('FDM Reimbursement - 2016','10576','DA');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('BPS Retrospective commons','10560','DA'),
	 ('BPS Retrospective Commons - Greening','10561','DA'),
	 ('BPS Retrospective Commons â€“ Young farmers','10562','DA'),
	 ('BPS Lump Sum','10570','DA'),
	 ('FDM Reimbursement - 2017','10577','DA'),
	 ('FDM Reimbursement -2018','10578','DA'),
	 ('FDM Reimbursement -2019','10579','DA'),
	 ('Additional Payment','80180','DA'),
	 ('SFI Interim','80199','DA'),
	 ('SFI Arable and Hort soils-Intro(AH1S)','80101','DA');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('SFI Arable and Hort soils-Intro(AH2S)','80102','DA'),
	 ('SFI Improved grasslands soils-Intro(IG1S)','80111','DA'),
	 ('SFI Improved grasslands soils-Intro(IG2S)','80112','DA'),
	 ('SFI Moorland(MR1G)','80121','DA'),
	 ('SFI Moorland-Additional Payment','80190','DA'),
	 ('Dairy Farmer','10260','DF'),
	 ('Dairy Farmer','10265','DF'),
	 ('Dairy Farmer','10266','DF'),
	 ('Dairy Farmer','10267','DF'),
	 ('Dairy Farmer','10268','DF');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Dairy Farmer','10269','DF'),
	 ('Dairy Farmer','10270','DF'),
	 ('Exceptional Adjustment Aid (Risk Management Training)','10282','DF'),
	 ('Exceptional Adjustment Aid (Small Dairy Farmer''s Scheme)','10283','DF'),
	 ('Dairy Response Fund','10290','DF'),
	 ('Interim Payment','10551','IP'),
	 ('Bridging Payment','10556','IP'),
	 ('Bridging Payment','10557','IP'),
	 ('BPS â€“ England element only','10558','IP'),
	 ('BPS Interim Payment','10559','IP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('SFI Pilot Contingency Payment','80015','IP'),
	 ('UK National Honey Programme R&D','23101','BK'),
	 ('SPS','10301','SPS'),
	 ('SPS-Partial','10302','SPS'),
	 ('Protein','10154','SPS'),
	 ('(CSS - Objective 1)','40161','NE-ALL'),
	 ('(CSS - Non- Objective 1)','40164','NE-ALL'),
	 ('(CSS - pre-RDR)','40181','NE-ALL'),
	 ('(ESA Rev Stage 1 - Obj 1)','40301','NE-ALL'),
	 ('(ESA Rev Stage 2 - Obj 1)','40302','NE-ALL');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('(ESA Rev Stage 1 - Non-Obj 1)','40303','NE-ALL'),
	 ('(ESA Rev Stage 2 - Non-Obj 1)','40304','NE-ALL'),
	 ('(ESA Rev Stage 3 - Non-Obj 1)','40305','NE-ALL'),
	 ('(ESA Rev Stage 4 - Non-Obj 1)','40306','NE-ALL'),
	 ('(ESA Conservation Plans Stage 1)','40358','NE-ALL'),
	 ('(ESA Conservation Plans Stage 2)','40359','NE-ALL'),
	 ('(ESA Conservation Plans Stage 3)','40360','NE-ALL'),
	 ('(ESA Conservation Plans Stage 4)','40361','NE-ALL'),
	 ('Habitat Improvement Former Set-aside','40502','NE-ALL'),
	 ('Habitat Improvement Saltmarsh','40504','NE-ALL');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Habitat Improvement Water Fringe','40506','NE-ALL'),
	 ('HLS Convergence','41201','NE-ALL'),
	 ('HLS Non-Convergence','41202','NE-ALL'),
	 ('ELS Convergence','41203','NE-ALL'),
	 ('ELS Non-Convergence','41204','NE-ALL'),
	 ('OELS Convergence','41205','NE-ALL'),
	 ('OELS Non-Convergence','41206','NE-ALL'),
	 ('ESS - HLS Capital Payments','41211','NE-ALL'),
	 ('ES Bridging Payment','48000','NE-ALL'),
	 ('ES Financial Support Payments','48005','NE-ALL');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('ES Treasury Payment','48010','NE-ALL'),
	 ('E/crops Miscanthus','40201','NE-AR'),
	 ('New Energy Crops Miscanthus','40203','NE-AR'),
	 ('New Energy Crops Short Rotation Coppice Non-Ag Land','40205','NE-AR'),
	 ('New Energy Crops Short Rotation Coppice Ag Land','40207','NE-AR'),
	 ('(Old Energy Crops obj 1 SRC Agri land)','40221','NE-AR'),
	 ('(ESA Rev Stage 1) Pre RDR','40353','NE-AR'),
	 ('(ESA Rev Stage 2) Pre RDR','40354','NE-AR'),
	 ('(ESA Rev Stage 3) Pre RDR','40355','NE-AR'),
	 ('(ESA Rev Stage 4) Pre RDR','40356','NE-AR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('(OF Objective 1)','40701','NE-AR'),
	 ('(OFS Maintenance Obj 1)','40702','NE-AR'),
	 ('(OFS Contribution Obj 1)','40703','NE-AR'),
	 ('(OF Non Obj 1)','40721','NE-AR'),
	 ('(OFS Maintenance Non- Obj 1)','40722','NE-AR'),
	 ('(OFS Contribution Non - obj 1)','40723','NE-AR'),
	 ('CSF - Capital Grants Scheme (Measure 1.125)','40907','NE-AR'),
	 ('CSF - Capital Grants Scheme (Measure 1.121)','40917','NE-AR'),
	 ('HLS - Historic Buildings Restoration (HTB)','40924','NE-AR'),
	 ('HLS - Access Capital (HAC)','40926','NE-AR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Paths for Communities','40996','NE-AR'),
	 ('ETIP - Farm Advice','41101','NE-AR'),
	 ('CSF Advice','41103','NE-AR'),
	 ('(ESS bridging payments - obj 1)','41208','NE-AR'),
	 ('(ESS bridging payments -Non-obj 1)','41209','NE-AR'),
	 ('CS Treasury Payment','47010','NE-AR'),
	 ('Improving the Economic Value of Forests','40231','FC-LS'),
	 ('(FWPS - Non-objective 1)','40402','FC-LS'),
	 ('(Farm Woodland Premium Scheme)','40451','FC-LS'),
	 ('(Farm Woodland Premium Scheme Former @ 25%)','40453','FC-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('(Farm Woodland Premium Scheme Former @ 50%)','40454','FC-LS'),
	 ('Woodland Grant Scheme New Planting','40600','FC-LS'),
	 ('Farm Woodland Premium Scheme','40605','FC-LS'),
	 ('Farm Woodland Scheme','40610','FC-LS'),
	 ('Woodland Assessment Grant','40615','FC-LS'),
	 ('Woodland Planning Grant','40620','FC-LS'),
	 ('Woodland Management Grant - Bio/Squirrel','40625','FC-LS'),
	 ('Woodland Improvement Grant - Bio/Squirrel','40630','FC-LS'),
	 ('Woodland Improvement Grant - SSSI','40635','FC-LS'),
	 ('Woodland Improvement Grant - Access/Health','40640','FC-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Woodland Creation Grant','40645','FC-LS'),
	 ('Farm Woodland Payment','40650','FC-LS'),
	 ('Woodland Regeneration Grant','40655','FC-LS'),
	 ('Woodfuel Timber','40660','FC-LS'),
	 ('Woodfuel Roads','40665','FC-LS'),
	 ('Woodland Improvement Grant - Plant Health','40670','FC-LS'),
	 ('Woodland Improvement Grant - Establishment Interim','40675','FC-LS'),
	 ('Woodland Improvement Grant - Maintenance Interim','40680','FC-LS'),
	 ('Rural land Registry Alignment (FC)','41308','FC-LS'),
	 ('Woodfuel Strategy (FC)','41309','FC-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('NELMS - Forestry Establishment','43600','FC-LS'),
	 ('NELMS - Forestry Maintenance','43605','FC-LS'),
	 ('NELMS - Forestry Capital Planning','43610','FC-LS'),
	 ('NELMS - Forestry Capital Improvement','43615','FC-LS'),
	 ('NELMS - Forestry Capital Regeneration','43620','FC-LS'),
	 ('NELMS - Forestry Capital Plant Health','43625','FC-LS'),
	 ('NELMS - Forestry Revenue','43630','FC-LS'),
	 ('Dedication','42600','FC-LS'),
	 ('Woodland Management Plan - Access','42610','FC-LS'),
	 ('Adding Value to Agricultural/Forestry Products','40901','RDT-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Setting up Management and Advisory Services','40903','RDT-LS'),
	 ('Basic Services','40904','RDT-LS'),
	 ('Diversification into Non-Agricultural Activities','40918','RDT-LS'),
	 ('Village Renewal & Development','40922','RDT-LS'),
	 ('Business Creation & Development','40928','RDT-LS'),
	 ('(RES Environ Protect Agri - Other Areas)','40930','RDT-LS'),
	 ('Use of Advisory Services','40936','RDT-LS'),
	 ('Co-operation for Development of New Products','40938','RDT-LS'),
	 ('Training for economic actors','40940','RDT-LS'),
	 ('Skills Acquisition','40942','RDT-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('LEADER: Competitiveness','40944','RDT-LS'),
	 ('LEADER: Environment/land Management','40946','RDT-LS'),
	 ('LEADER: Quality of Life / Diversification','40948','RDT-LS'),
	 ('LEADER: Co-operation Projects','40950','RDT-LS'),
	 ('LEADER: Running Local Action Groups','40952','RDT-LS'),
	 ('REG - Farm modernisation of Agricultural Holdings','40954','RDT-LS'),
	 ('FFIS - Farm modernisation of Agricultural Holdings','40956','RDT-LS'),
	 ('REG - Improving the Economic Value of Forests','40958','RDT-LS'),
	 ('FFIS - Improving the Economic Value of Forests','40960','RDT-LS'),
	 ('REG - Adding Value to Agricultural/Forestry Products','40962','RDT-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('FFIS - Adding Value to Agricultural/Forestry Products','40964','RDT-LS'),
	 ('REG - Co-operation for Development of New Products','40966','RDT-LS'),
	 ('FFIS - Co-operation for Development of New Products','40968','RDT-LS'),
	 ('REG -Infrastructure for Development of New Products','40970','RDT-LS'),
	 ('FFIS -Infrastructure for Development of New Products','40972','RDT-LS'),
	 ('REG - Diversification into Non-Agricultural Activities','40974','RDT-LS'),
	 ('REG - Micro-enterprises','40976','RDT-LS'),
	 ('FFIS - Micro-enterprises','40978','RDT-LS'),
	 ('REG - Encouragement of Tourism','40980','RDT-LS'),
	 ('REG - Basic Services','40982','RDT-LS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Skills & RCBF Basic Services','40984','RDT-LS'),
	 ('REG - Village Renewal & Development','40986','RDT-LS'),
	 ('REG - Conservation of Rural Heritage','40988','RDT-LS'),
	 ('REG -Training for economic actors','40990','RDT-LS'),
	 ('Skills & RCBF Training for economic actors','40992','RDT-LS'),
	 ('REG - Skills Acquisition','40994','RDT-LS'),
	 ('REG-Rural heritage (Convergence)','40998','RDT-LS'),
	 ('REG -Vocational Training  and Information','41105','RDT-LS'),
	 ('Skills & RCBF -Vocational Training  and Information','41107','RDT-LS'),
	 ('Beef Carcase Classification Scheme','1611','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Pig Carcase Classification Scheme','1621','TR'),
	 ('Deadweight Price Reporting Scheme','1631','TR'),
	 ('Intervention Beef','3111','TR'),
	 ('Intervention Butter','3211','TR'),
	 ('Intervention Skimmed Milk Powder','3311','TR'),
	 ('Intervention Cereals','3410','TR'),
	 ('Intervention Barley','3411','TR'),
	 ('Intervention Wheat','3412','TR'),
	 ('Intervention Rye','3413','TR'),
	 ('Sugar Restructuring Aid','10312','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Butter Private Storage Costs Balance','20121','TR'),
	 ('Private Storage Aid - Pigmeat','20125','TR'),
	 ('MCL Creamery Deliveries','20151','TR'),
	 ('Production Aid for Dried Fodder','23001','TR'),
	 ('UK National Honey Programme R&D','23101','TR'),
	 ('Short Flax Advance Final Payment','23205','TR'),
	 ('Aid for Hemp','23301','TR'),
	 ('Fruit & Veg Withdrawal Compensation and','25001','TR'),
	 ('F&V  Producer Organisation Aid','25051','TR'),
	 ('F&V  Producer Organisation Aid - Advance','25052','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('F&V Operational Programmes Balance','25053','TR'),
	 ('F&V Operational Programmes - Application','25054','TR'),
	 ('F&V Transitional Provisions - Operational','25055','TR'),
	 ('F&V Operational Programmes Advance/Partial','25056','TR'),
	 ('Financial Compensation for Fish Withdraw','26111','TR'),
	 ('Internal Market promotion reg 94/2002 Co','28001','TR'),
	 ('Promotional Measures Beef R94/02 Contrac','28002','TR'),
	 ('Promotional Measures Live Plants & Flori','28003','TR'),
	 ('Promotional Measures Organic Farming R94','28004','TR'),
	 ('Milk Products R94/02 Promotions C(04)200','28005','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Quality Beef R94/02 Promotions C(04)2000','28006','TR'),
	 ('Promotions Milk Decision No. C(2004) 536','28007','TR'),
	 ('Promotions Milk Decision No. C(05) 1767','28008','TR'),
	 ('Promotions Milk Decision No. C(05) 1767','28009','TR'),
	 ('Promotions Meat Products Decision  C(200','28010','TR'),
	 ('Promotions Meat Products Decision  C(200','28011','TR'),
	 ('Promotions Meat Products Decision C(06)','28012','TR'),
	 ('Promotions Milk and Milk Products Decisi','28013','TR'),
	 ('Promotions Quality Meat Decision C(2009)','28014','TR'),
	 ('Promotions Milk & Milk Products Decision','28015','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Promotions Decision C(08)3738 Programme','28016','TR'),
	 ('Promotions Decision C(08)3738 Programme','28017','TR'),
	 ('Promotions Decision C(10) 4312-Multinat.','28018','TR'),
	 ('Promotions Decision C(10) 4312- Programme','28019','TR'),
	 ('Promotions Decision C(11) 4611- Programme','28020','TR'),
	 ('Promotions INP/BLSA/2011/1','28021','TR'),
	 ('Promotions INP/QMS/2012/1','28022','TR'),
	 ('Promotions INP/DCNI/2012/1/UK','28023','TR'),
	 ('Promotions INP/SUSTAIN/2013/1','28024','TR'),
	 ('Promotions INP/BGA/2014/1','28025','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Promotions INP/DCNI/2014/1/UK','28026','TR'),
	 ('Promotions INP/AHDB-ENLEX/2014/2/UK','28027','TR'),
	 ('Promotions INP/HCC/2014/01','28028','TR'),
	 ('Promotions Contract EXP/DCNI/2014/1','28029','TR'),
	 ('Promotions INP/QMS/2015/1','28030','TR'),
	 ('Promotions INP/AHDB-PC/2015/1/UK','28031','TR'),
	 ('Milk Quota Penalties','29001','TR'),
	 ('School Milk - LA Subsidy England (2008 onwards)','29011','TR'),
	 ('School Milk - LA Subsidy Scotland (2008 onwards)','29012','TR'),
	 ('School Milk - LA Subsidy Wales (2008 onwards)','29013','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('School Milk - Non LA Subsidy  (2008 onwards)','29014','TR'),
	 ('Export Refunds Cereals','30100','TR'),
	 ('Export Refunds Common Wheat Grain and Fl','30101','TR'),
	 ('Export Refund Barley Grain and Malt','30102','TR'),
	 ('Export Refund Maize','30103','TR'),
	 ('Export Refund Other Cereals','30104','TR'),
	 ('Export Refunds on Sugar and Isoglucose','30111','TR'),
	 ('Export Refunds - Fresh Fruit & Veg','30121','TR'),
	 ('Export Refunds Processed F&V','30131','TR'),
	 ('Export Refunds on Rice','30141','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Export Refunds on Olive Oil','30151','TR'),
	 ('Export Refunds on Butter','30201','TR'),
	 ('Export Refunds on Skimmed Milk Powder','30202','TR'),
	 ('Export Refunds on Cheese','30203','TR'),
	 ('Exp refund Powdered Milk with a Fat > 1.','30204','TR'),
	 ('Export Refund Condensed Milk','30205','TR'),
	 ('Export Refund Other Milk Products','30206','TR'),
	 ('Export Refund Beef','30210','TR'),
	 ('Export Refund Beef Tinned Meat','30211','TR'),
	 ('Export Refund Frozen Beef/Veal Carcasses','30213','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Export Refund Frozen Beef/Veal Quarters','30214','TR'),
	 ('Export Refund Frozen Beef/Veal Boneless','30215','TR'),
	 ('Export Refund Fresh Beef/Veal Boneless','30216','TR'),
	 ('Export Refund FreshBeef/Veal Carcasses','30217','TR'),
	 ('Export Refund Fresh Beef/Veal Quarters','30218','TR'),
	 ('Export Refunds Pigmeat - Carcasses and o','30230','TR'),
	 ('Export Refunds Pigmeat - Dried, Salted M','30231','TR'),
	 ('Export Refunds Pigmeat - Sausages and Co','30232','TR'),
	 ('Export Refunds Pigmeat - Others','30233','TR'),
	 ('Export Refunds Eggs for Hatching','30241','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Export Refunds Eggs in Shell','30242','TR'),
	 ('Export Refunds Egg Products','30243','TR'),
	 ('Export Refunds for Poultry - Other Poult','30251','TR'),
	 ('Export Refunds for Poultry - Chicks','30252','TR'),
	 ('Export Refund Whisky','30301','TR'),
	 ('Export Refund barley based spirits','30302','TR'),
	 ('Export Refund Wheat based spirits','30303','TR'),
	 ('Exp Refund Proc. goods Cereals and Rice','30311','TR'),
	 ('Exp Refunds Proc Goods Sugar and Isogluc','30312','TR'),
	 ('Export Reund Proc Goods SMP or Similar P','30313','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Exp Refund Proc Goods Whole Milk Powder','30314','TR'),
	 ('Export Refund Processed Goods Butter','30315','TR'),
	 ('Export Refund Processed Goods Eggs','30316','TR'),
	 ('Export Refund Processed Goods Other Agri','30317','TR'),
	 ('Sugar Production','65101','TR'),
	 ('Slaughter Incentive Payment Scheme','10284','TR'),
	 ('School Milk - LA Subsidy England (2017 onwards)','29111','TR'),
	 ('School Milk - LA Subsidy Scotland (2017 onwards)','29112','TR'),
	 ('School Milk - LA Subsidy Wales (2017 onwards)','29113','TR'),
	 ('School Milk - Non LA Subsidy (2017 onwards)','29114','TR');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Woodland Improvement- Infrastructure - M04 FA4a','5274A','FC-CS'),
	 ('Woodland Creation - M08 FA4a','5514A','FC-CS'),
	 ('Woodland Creation - M08 FA4b','5514B','FC-CS'),
	 ('Woodland Planning - M08 FA4a','5524A','FC-CS'),
	 ('Woodland Improvement Capital - Other - M08 FA4a','5534A','FC-CS'),
	 ('Woodland Improvement Capital - Other - M08 FA4b','5534B','FC-CS'),
	 ('Woodland Restoration - Plant Health - M08 FA4a','5544A','FC-CS'),
	 ('Woodland Improvement Capital - Plant Health - M08 FA4a','5554A','FC-CS'),
	 ('Woodland Planning - M08 FA4a','5564A','FC-CS'),
	 ('Woodland Improvement - Multi-Annual - M15 FA4a','5904A','FC-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS - Forestry Establishment Maintenance â€“ M08 FA4a','5556A','FC-CS'),
	 ('CS - Forestry Establishment Maintenance â€“ M08 FA4b','5556B','FC-CS'),
	 ('Forestry Commission','40605','FC-CS'),
	 ('England Woodland Creation Offer (EWCO)','11785','FC-CS'),
	 ('CS Financial Support Payments','47005','NE-CS'),
	 ('Water Environment Grant Scheme â€“ M07 FA4a','5444A','NE-CS'),
	 ('CS Water Advice - M02 FA4b','5104B','NE-CS'),
	 ('CS Advice - M02 FA4a','5114A','NE-CS'),
	 ('CS Advice - M02 FA4b','5114B','NE-CS'),
	 ('CS Advice - M02 FA4c','5114C','NE-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS RP Water Options - M04 FA4b','5204B','NE-CS'),
	 ('CS Standalone Boundary - M04 FA4a','5214A','NE-CS'),
	 ('CS Standalone Boundary - M04 FA4b','5214B','NE-CS'),
	 ('CS Standalone Boundary - M04 FA4c','5214C','NE-CS'),
	 ('CS Priority Area Capital - M04 FA4a','5224A','NE-CS'),
	 ('CS Priority Area Capital - M04 FA4b','5224B','NE-CS'),
	 ('CS Priority Area Capital - M04 FA4c','5224C','NE-CS'),
	 ('CS Priority Sites Capital - M04 FA4d','5234A','NE-CS'),
	 ('CS Priority Sites Capital - M04 FA4b','5234B','NE-CS'),
	 ('CS Priority Sites Capital - M04 FA4c','5234C','NE-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Access Capital - M04 FA4a','5244A','NE-CS'),
	 ('CS Access Capital - M04 FA4b','5244B','NE-CS'),
	 ('CS Access Capital - M04 FA4c','5244C','NE-CS'),
	 ('CS Higher Tier Revenue - M10 FA4a','5604A','NE-CS'),
	 ('CS Higher Tier Revenue - M10 FA4b','5604B','NE-CS'),
	 ('CS Higher Tier Revenue - M10 FA4c','5604C','NE-CS'),
	 ('CS Access Revenue - M10 FA4a','5614A','NE-CS'),
	 ('CS Access Revenue - M10 FA4b','5614B','NE-CS'),
	 ('CS Access Revenue - M10 FA4c','5614C','NE-CS'),
	 ('CS Mid Tier Revenue - M10 FA4a','5704A','NE-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Mid Tier Revenue - M10 FA4b','5704B','NE-CS'),
	 ('CS Mid Tier Revenue - M10 FA4c','5704C','NE-CS'),
	 ('CS Organic Conversion - M11 FA4a','5804A','NE-CS'),
	 ('CS Organic Conversion - M11 FA4b','5804B','NE-CS'),
	 ('CS Organic Conversion - M11 FA4c','5804C','NE-CS'),
	 ('CS Organic Maintenance - M11 FA4a','5814A','NE-CS'),
	 ('CS Organic Maintenance - M11 FA4b','5814B','NE-CS'),
	 ('CS Organic Maintenance - M11 FA4c','5814C','NE-CS'),
	 ('CSF Staffing - M02 FA4a','5154A','NE-CS'),
	 ('CSF Training â€“ M02 FA4a','5164A','NE-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('ECP (England Coastal Paths) â€“ M07 FA6b','5436B','NE-CS'),
	 ('CS Bridging payment','47000','NE-CS'),
	 ('Countryside Stewardship Higher Tier Capital - M04 FA4a','5234A','NE-CS'),
	 ('Woodland Improvement- Infrastructure - M04 FA4a','5274A','NE-CS'),
	 ('Woodland Creation - M08 FA4a','5514A','NE-CS'),
	 ('Woodland Creation - M08 FA4b','5514B','NE-CS'),
	 ('Woodland Planning - M08 FA4a','5524A','FC-CS'),
	 ('Woodland Improvement Capital - Other - M08 FA4a','5534A','FC-CS'),
	 ('Woodland Improvement Capital - Other - M08 FA4b','5534B','FC-CS'),
	 ('Woodland Restoration - Plant Health - M08 FA4a','5544A','FC-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Woodland Improvement Capital - Plant Health - M08 FA4a','5554A','FC-CS'),
	 ('Woodland Improvement - Multi-Annual - M15 FA4a','5904A','FC-CS'),
	 ('CS - Forestry Establishment Maintenance â€“ M08 FA4a','5556A','FC-CS'),
	 ('CS - Forestry Establishment Maintenance â€“ M08 FA4b','5556B','FC-CS'),
	 ('Nature Improvement Area Grant - M16 FA4a','6004A','FC-CS'),
	 ('Nature Improvement Area Grant - M16 FA4b','6004B','FC-CS'),
	 ('Nature Improvement Area Grant - M16 FA4c','6004C','FC-CS'),
	 ('Water Environment Grant (WEG) Direct Contracting â€“ M07 FA4a','5454A','NE-CS'),
	 ('CS Treasury Payment','47010','NE-CS'),
	 ('CS Historic Building Capital - M07 FA4a','5414A','NE-CS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Historic Building Capital - M07 FA4b','5414B','NE-CS'),
	 ('CS Historic Building Capital - M07 FA4c','5414C','NE-CS'),
	 ('CP - M01 FA2a','5002A','RDT-CP'),
	 ('CP - M01 FA3a','5003A','RDT-CP'),
	 ('CP - M01 FA3b','5003B','RDT-CP'),
	 ('CP - M01 FA5a','5005A','RDT-CP'),
	 ('CP - M01 FA5b','5005B','RDT-CP'),
	 ('CP - M01 FA5c','5005C','RDT-CP'),
	 ('CP - M01 FA5d','5005D','RDT-CP'),
	 ('Growth - M01 FA6b','5016B','RDT-CP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CP - M02 FA2a','5122A','RDT-CP'),
	 ('CP - M02 FA2b','5122B','RDT-CP'),
	 ('CP - M02 FA3a','5123A','RDT-CP'),
	 ('CP - M02 FA3b','5123B','RDT-CP'),
	 ('CP - M02 FA5a','5125A','RDT-CP'),
	 ('CP - M02 FA5b','5125B','RDT-CP'),
	 ('CP - M02 FA5c','5125C','RDT-CP'),
	 ('CP - M02 FA5d','5125D','RDT-CP'),
	 ('Growth - M02 FA6b','5136B','RDT-CP'),
	 ('CP - M04 FA2a','5262A','RDT-CP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CP - M04 FA5a','5265A','RDT-CP'),
	 ('CP - M04 FA5b','5265B','RDT-CP'),
	 ('CP - M04 FA5c','5265C','RDT-CP'),
	 ('CP - M04 FA5d','5265D','RDT-CP'),
	 ('CP (FRF)- M05 FA3b','5293B','RDT-CP'),
	 ('CP - M06 FA2b','5302B','RDT-CP'),
	 ('Growth - M06 FA6a','5316A','RDT-CP'),
	 ('Growth - M07 FA6b','5426B','RDT-CP'),
	 ('Growth - M07 FA6c','5426C','RDT-CP'),
	 ('CP - M08 FA5c','5505C','RDT-CP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CP - M16 FA2a','6012A','RDT-CP'),
	 ('CP - M16 FA3a','6013A','RDT-CP'),
	 ('CP - M16 FA3b','6013B','RDT-CP'),
	 ('Growth - M16 FA6a','6026A','RDT-CP'),
	 ('Growth - M16 FA6b','6026B','RDT-CP'),
	 ('Growth - M04 FA6a','5286A','RDT-CP'),
	 ('Growth - M08 FA6a','5566A','RDT-CP'),
	 ('Leader - M19 FA6a','6106A','RDT-CP'),
	 ('Farming Equipment & Technology Fund (FETF)','15011','RDT-CP'),
	 ('Farming Transformation Fund - Water Management','15021','RDT-CP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Farming Transformation Fund â€“ Improving Farm Productivity','15022','RDT-CP'),
	 ('Farming Transformation Fund â€“ Adding Value','15023','RDT-CP'),
	 ('FETF-Round 2 Productivity Slurry','15012','RDT-CP'),
	 ('FETF-Round 2 AHW','15013','RDT-CP'),
	 ('FTF-Water-Round 2','15031','RDT-CP'),
	 ('FTF-Productivity Round 2','15032','RDT-CP'),
	 ('FTF-Slurry Infrastructure','15024','RDT-CP'),
	 ('FTF-Slurry Infrastructure Round 2','15034','RDT-CP'),
	 ('FTFâ€“AHWâ€“Cattle','15101','RDT-CP'),
	 ('FTFâ€“AHWâ€“Pig','15102','RDT-CP');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('FTFâ€“AHWâ€“Poultry','15103','RDT-CP'),
	 ('Farming Recovery Fund','15001','RDT-CP'),
	 ('Fly Tipping ( C )','17001','RDT-CP'),
	 ('Fly Tipping ( R )','17011','RDT-CP'),
	 ('ERDP ex post Evaluation','700NA','RDPECS'),
	 ('The RDPE Rural network','701NA','RDPECS'),
	 ('The RDPE National Rural Network','702NA','RDPECS'),
	 ('RDPE mid-term Evaluation','703NA','RDPECS'),
	 ('Rural land Registry Alignment (NE)','704NA','RDPECS'),
	 ('ESS Monitoring & Evaluation (NE/ELM Contracts)','705NA','RDPECS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('ESS Monitoring & Evaluation (ELM Contracts)','706NA','RDPECS'),
	 ('Rural land Registry Alignment (FC)','707NA','RDPECS'),
	 ('Woodfuel Strategy (FC)','708NA','RDPECS'),
	 ('Axis 1 & 3 evaluation','709NA','RDPECS'),
	 ('Leader evaluation','710NA','RDPECS'),
	 ('Woodland Owners Segmentation Study','711NA','RDPECS'),
	 ('Paths for Communities evaluation','712NA','RDPECS'),
	 ('Strategic Environmental Assessement','713NA','RDPECS'),
	 ('Leader Transition Fund','714NA','RDPECS'),
	 ('RDPE Programme Monitoring Committee:','715NA','RDPECS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Unassigned until new RDPE TA project confirmed','716NA','RDPECS'),
	 ('LFA Consultancy (ELM)','717NA','RDPECS'),
	 ('ESS Monitoring & Evaluation (NE SHINE Contracts)','718NA','RDPECS'),
	 ('New Programme ex ante evaluation','719NA','RDPECS'),
	 ('2007-13 RDPE TA Transition support: NE','720NA','RDPECS'),
	 ('2007-13 RDPE TA Transition support: RPA','721NA','RDPECS'),
	 ('2007-13 RDPE TA Transition support: CAPD','722NA','RDPECS'),
	 ('2007-13 RPDE TA Transition support: FC','723NA','RDPECS'),
	 ('CSF Staffing - M02 FA4a','5154A','RDPECS'),
	 ('CSF Training â€“ M02 FA4a','5164A','RDPECS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CSF Training Â - M01 FA5D','5025D','RDPECS'),
	 ('CSF Demos â€“ M01 FA5D','5035D','RDPECS'),
	 ('CSF Staffing â€“ M02 FA4B','5154B','RDPECS'),
	 ('CSF Training â€“ M02 FA4B','5164B','RDPECS'),
	 ('CSF Training - M01 FA4b','5024B','RDPECS'),
	 ('CSF Demos - M01 FA4b','5034B','RDPECS'),
	 ('Aftercare â€“ M02 FA4a','5174A','RDPECS'),
	 ('ERDP ex post Evaluation','41301','RDPELS'),
	 ('the RDPE Rural network','41302','RDPELS'),
	 ('the UK National Rural Network','41303','RDPELS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('RDPE mid-term Evaluation','41304','RDPELS'),
	 ('Rural land Registry Alignment (NE)','41305','RDPELS'),
	 ('ESS Monitoring & Evaluation (NE Contracts)','41306','RDPELS'),
	 ('ESS Monitoring & Evaluation (ELM Contracts)','41307','RDPELS'),
	 ('Rural land Registry Alignment (FC)','41308','RDPELS'),
	 ('Woodfuel Strategy (FC)','41309','RDPELS'),
	 ('RDPE TA - Axis 1 & 3 evaluation','41310','RDPELS'),
	 ('RDPE TA - Leader evaluation','41311','RDPELS'),
	 ('RDPE TA - Woodland Owners Segmentation Study','41312','RDPELS'),
	 ('RDPE TA - Paths for Communties evaluation','41313','RDPELS');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Woodfuel Strategy (RDT - North East)','41314','RDPELS'),
	 ('Woodfuel Strategy (RDTs - Southeast)','41315','RDPELS'),
	 ('Woodfuel Strategy (RDTs - Southwest)','41316','RDPELS'),
	 ('Woodfuel Strategy (RDTs - Yorkshire)','41317','RDPELS'),
	 ('LFA Consultancy (ELM)','41318','RDPELS'),
	 ('ESS Monitoring & Evaluation (NE/ELM Contracts: SHINE)','41319','RDPELS'),
	 ('New Programme ex ante evaluation','41320','RDPELS'),
	 ('Rural Development programme (2014-2020)','43001','OPA'),
	 ('Crofting Counties Agricultural Grants Scheme','43101','OPA'),
	 ('Rural Priorities','43102','OPA');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Forestry Commission Scotland - LMO','43103','OPA'),
	 ('Food Processing, Marketing & Co-operation (FPMC)','43104','OPA'),
	 ('Land Managers Options','43105','OPA'),
	 ('Rural Priorities','43201','OPA'),
	 ('CS RP Water Options - M04 FA4b','5204B','P1'),
	 ('CS Stdalone Bound. - M04 FA4a','5214A','P1'),
	 ('CS Stdalone Bound. - M04 FA4b','5214B','P1'),
	 ('CS Stdalone Bound. - M04 FA4c','5214C','P1'),
	 ('CS Prior. Area Cap - M04 FA4a','5224A','P1'),
	 ('CS Prior. Area Cap - M04 FA4b','5224B','P1');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Prior. Area Cap - M04 FA4c','5224C','P1'),
	 ('CS Prior. Sites Cap - M04 FA4d','5234A','P1'),
	 ('CS Prior. Sites Cap - M04 FA4b','5234B','P1'),
	 ('CS Prior. Sites Cap - M04 FA4c','5234C','P1'),
	 ('CS Access Cap - M04 FA4a','5244A','P1'),
	 ('CS Access Cap - M04 FA4b','5244B','P1'),
	 ('CS Access Cap - M04 FA4c','5244C','P1'),
	 ('Wood. Improv. Infra. - M04 FA4a','5274A','P1'),
	 ('CS Higher Tier Rev - M10 FA4a','5604A','P1'),
	 ('CS Higher Tier Rev - M10 FA4b','5604B','P1');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Higher Tier Rev - M10 FA4c','5604C','P1'),
	 ('CS Access Rev - M10 FA4a','5614A','P1'),
	 ('CS Access Rev - M10 FA4b','5614B','P1'),
	 ('CS Access Rev - M10 FA4c','5614C','P1'),
	 ('CS Mid Tier Rev - M10 FA4a','5704A','P1'),
	 ('CS Mid Tier Rev - M10 FA4b','5704B','P1'),
	 ('CS Mid Tier Rev - M10 FA4c','5704C','P1'),
	 ('CS Organic Conversion - M11 FA4a','5804A','P1'),
	 ('CS Organic Conversion - M11 FA4b','5804B','P1'),
	 ('CS Organic Conversion - M11 FA4c','5804C','P1');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('CS Organic Maintenance - M11 FA4a','5814A','P1'),
	 ('CS Organic Maintenance - M11 FA4b','5814B','P1'),
	 ('CS Organic Maintenance - M11 FA4c','5814C','P1'),
	 ('Woodland Creation - M08 FA4a','5514A','P1'),
	 ('Woodland Creation - M08 FA4b','5514B','P1'),
	 ('Woodland Planning - M08 FA4a','5524A','P1'),
	 ('Woodland Improv Capital - Other - M08 FA4a','5534A','P1'),
	 ('Woodland Improv Capital - Other - M08 FA4b','5534B','P1'),
	 ('Woodland Restoration - Plant Health - M08 FA4a','5544A','P1'),
	 ('Woodland Improv Capital - Plant Health - M08 FA4a','5554A','P1');
INSERT INTO rpa_mit_invoices.public.lookup_schemecodes (description,code,org) VALUES
	 ('Woodland Maintenance - MA8 FA4b','5564B','P1'),
	 ('Woodland Maintenance - MA8 FA4a','5564A','P1'),
	 ('Woodland Improv - Multi-Annual - M15 FA4a','5904A','P1'),
	 ('Domestic Facilitation Payment','81001','P1'),
	 ('WEG (EA WFD) - M07 FA4a','5464A','EA'),
	 ('WEG (EA WFD) - M07 FA4a','5464A','EACS'),
	 ('Farming Equipment Technology Fund','15011','RDT');
