- key: POSTGRES__HOST  
  value: "{{servicename}}-HOST" 
  type: "keyvault"
- key: POSTGRES__USER
  value: "{{servicename}}-POSTGRES-USER" 
  type: "keyvault"
- key: POSTGRES__DATABASE
  value: "{{servicename}}-POSTGRES-DATABASE" 
  type: "keyvault"
- key: POSTGRES__TOKEN_SCOPES
  value: "{{servicename}}-POSTGRES-TOKEN-SCOPES" 
  type: "keyvault"
- key: POSTGRES__MANAGEDIDENTITYCLIENTID 
  value: "{{servicename}}-POSTGRES-MANAGEDIDENTITY-CLIENTID" 
  type: "keyvault"
- key: TENANTID
  value: "{{servicename}}-TENANT-ID" 
  type: "keyvault"
- key: CLIENTID
  value: "{{servicename}}-CLIENT-ID" 
  type: "keyvault"
- key: GOVNOTIFY__APIKEY
  value: "{{servicename}}-GOVNOTIFY-APIKEY" 
  type: "keyvault"
- key: PAYMENTHUB__CONNECTION
  value: "{{servicename}}-PAYMENTHUB-CONNECTION" 
  type: "keyvault"
- key: PAYMENTHUB__TOPIC
  value: "{{servicename}}-PAYMENTHUB-TOPIC" 
  type: "keyvault"
- key: PAYMENTHUB__RESPONSE_TOPIC
  value: "{{servicename}}-PAYMENTHUB-RESPONSE-TOPIC" 
  type: "keyvault"
- key: PAYMENTHUB__RESPONSE_SUBSCRIPTION
  value: "{{servicename}}-PAYMENTHUB-RESPONSE-SUBSCRIPTION" 
  type: "keyvault"
- key: APPINSIGHTS__CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"
