- key: POSTGRES-HOST  
  value: "{{servicename}}-POSTGRES-HOST" 
  type: "keyvault"
- key: POSTGRES-USER
  value: "{{servicename}}-POSTGRES-USER" 
  type: "keyvault"
- key: POSTGRES-DATABASE
  value: "{{servicename}}-POSTGRES-DATABASE" 
  type: "keyvault"
- key: POSTGRES-TOKEN-SCOPES
  value: "{{servicename}}-POSTGRES-TOKEN-SCOPES" 
  type: "keyvault"
- key: POSTGRES-MANAGEDIDENTITY-CLIENTID
  value: "{{servicename}}-POSTGRES-MANAGEDIDENTITY-CLIENTID" 
  type: "keyvault"
- key: GOVNOTIFY-API-KEY
  value: "{{servicename}}-GOVNOTIFY-API-KEY" 
  type: "keyvault"
- key: PAYMENTHUB-CONNECTION
  value: "{{servicename}}-PAYMENTHUB-CONNECTION" 
  type: "keyvault"
- key: PAYMENTHUB-TOPIC
  value: "{{servicename}}-PAYMENTHUB-TOPIC" 
  type: "keyvault"
- key: APPINSIGHTS-CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"