- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps4401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "sndadpinfmi4401-ffc-demo-payment-service" 
- key: EVENT_HOST
  value: "sndadpinfen3001"  
- key: POSTGRES_DB
  value: "lap_mit_invoices"