- key: POSTGRES:HOST
  value: ""
- key: POSTGRES:USER
  value: ""
- key: POSTGRES:DATABASE
  value: ""
- key: POSTGRES:TOKEN_SCOPES
  value: ""
- key: POSTGRES:MANAGEDIDENTITY_CLIENTID
  value: ""
- key: GOVNOTYIFY:API_KEY
  value: ""
- key: PAYMENTHUB:rpa-mit-manual-templates-api_CONN_PAYMENTHUB
  value: ""