- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}" 
  
# SECRETS CAN BE ADDED THIS WAY
- key: CONNECTIONSTRING
  value: "Server=127.0.0.1;Database=rpa_mit_invoices;Username=postgres;Password=ghjiUIbfds345;" 
  type: "keyvault"
- key: ADINSTANCE
  value: "https://login.microsoftonline.com/" 
  type: "keyvault"
- key: ADTENANTID
  value: "6f504113-6b64-43f2-ade9-242e057800" 
  type: "keyvault"
- key: ADDOMAIN
  value: "defra.onmicrosoft.com/" 
  type: "keyvault"
- key: ADCLIENTID
  value: "f2d4ac8e-632a-41ff-b83a-e5d39e7d095a" 
  type: "keyvault"
- key: ADCALLBACKPATH
  value: "/signin-oidc" 
  type: "keyvault"
- key: EVENTQUEUENAME
  value: "rpa-mit-events" 
  type: "keyvault"
- key: IMPORTERQUEUENAME
  value: "rpa-mit-invoice-importer" 
  type: "keyvault"
- key: BLOBCONTAINERNAME
  value: "invoices" 
  type: "keyvault"
- key: BLOBCONNECTIONSTRING
  value: "UseDevelopmentStorage=true" 
  type: "keyvault"
- key: NOTIFICATIONQUEUENAME
  value: "rpa-mit-invoice-notification" 
  type: "keyvault"
- key: SERVICEBUSNAMESPACE
  value: "sb://stablemitsb.servicebus.windows.net" 
  type: "keyvault"
- key: INVOICEAPIBASEURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: APPLICATIONBASEURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: PAYMENTGENERATORQUEUENAME
  value: "rpa-mit-payment" 
  type: "keyvault"