- key: POSTGRES_HOST  
  value: "{{servicename}}-POSTGRES-HOST" 
  type: "keyvault"
- key: POSTGRES_USER
  value: "{{servicename}}-POSTGRES-USER" 
  type: "keyvault"
- key: POSTGRES_DATABASE
  value: "{{servicename}}-POSTGRES-DATABASE" 
  type: "keyvault"
- key: POSTGRES_TOKEN_SCOPES
  value: "{{servicename}}-POSTGRES-TOKEN-SCOPES" 
  type: "keyvault"
- key: POSTGRES_MANAGEDIDENTITY_CLIENTID
  value: "{{servicename}}-POSTGRES-MANAGEDIDENTITY-CLIENTID" 
  type: "keyvault"
- key: GOVNOTIFY_API_KEY
  value: "{{servicename}}-GOVNOTIFY-API-KEY" 
  type: "keyvault"
- key: PAYMENTHUB_CONNECTION
  value: "{{servicename}}-PAYMENTHUB-CONNECTION" 
  type: "keyvault"
- key: PAYMENTHUB_TOPIC
  value: "{{servicename}}-PAYMENTHUB-TOPIC" 
  type: "keyvault"
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"