- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}" 
  
# SECRETS CAN BE ADDED THIS WAY
- key: ConnectionStrings:PostGres
  value: "Server=127.0.0.1;Database=rpa_mit_invoices;Username=postgres;Password=ghjiUIbfds345;" 
  type: "keyvault"
- key: AzureAd:Instance
  value: "https://login.microsoftonline.com/" 
  type: "keyvault"
- key: AzureAd:TenantId
  value: "6f504113-6b64-43f2-ade9-242e057800" 
  type: "keyvault"
- key: AzureAd:Domain
  value: "defra.onmicrosoft.com/" 
  type: "keyvault"
- key: AzureAd:ClientId
  value: "f2d4ac8e-632a-41ff-b83a-e5d39e7d095a" 
  type: "keyvault"
- key: AzureAd:CallbackPath
  value: "/signin-oidc" 
  type: "keyvault"
- key: EventQueueName
  value: "rpa-mit-events" 
  type: "keyvault"
- key: ImporterQueueName
  value: "rpa-mit-invoice-importer" 
  type: "keyvault"
- key: BlobContainerName
  value: "invoices" 
  type: "keyvault"
- key: BlobConnectionString
  value: "UseDevelopmentStorage=true" 
  type: "keyvault"
- key: NotificationQueueName
  value: "rpa-mit-invoice-notification" 
  type: "keyvault"
- key: ServiceBusNamespace
  value: "sb://stablemitsb.servicebus.windows.net" 
  type: "keyvault"
- key: InvoiceAPIBaseURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: ApprovalAPIBAseURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: ReferenceDataAPIBaseURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: InvoiceImporterAPIBaseURI
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: ApplicationBaseUri
  value: "https://localhost:7012/" 
  type: "keyvault"
- key: PaymentGeneratorQueueName
  value: "rpa-mit-payment" 
  type: "keyvault"