- key: POSTGRES__HOST  
  value: "{{servicename}}-HOST" 
  type: "keyvault"
- key: POSTGRES__USER
  value: "{{servicename}}-POSTGRES-USER" 
  type: "keyvault"
- key: POSTGRES__DATABASE
  value: "{{servicename}}-POSTGRES-DATABASE" 
  type: "keyvault"
- key: POSTGRES__TOKEN_SCOPES
  value: "{{servicename}}-POSTGRES-TOKEN-SCOPES" 
  type: "keyvault"
- key: POSTGRES__MANAGEDIDENTITYCLIENTID 
  value: "{{servicename}}-POSTGRES-MANAGEDIDENTITY-CLIENTID" 
  type: "keyvault"
- key: GOVNOTIFY__APIKEY
  value: "{{servicename}}-GOVNOTIFY-APIKEY" 
  type: "keyvault"
- key: PAYMENTHUB__CONNECTION
  value: "{{servicename}}-PAYMENTHUB-CONNECTION" 
  type: "keyvault"
- key: PAYMENTHUB__TOPIC
  value: "{{servicename}}-PAYMENTHUB-TOPIC" 
  type: "keyvault"
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"