@Rpa.Mit.Manual.Templates.Api.Api_HostAddress = https://localhost:7118

GET {{Rpa.Mit.Manual.Templates.Api.Api_HostAddress}}/api/demo

###

POST {{Rpa.Mit.Manual.Templates.Api.Api_HostAddress}}/api/demo
Content-Type: application/json

{
    "name":"item3"
}

###

PATCH {{Rpa.Mit.Manual.Templates.Api.Api_HostAddress}}/api/demo
Content-Type: application/json

{
    "id":"1",
    "name":"item3"
}

###

GET {{Rpa.Mit.Manual.Templates.Api.Api_HostAddress}}/api/demo/1

###

DELETE {{Rpa.Mit.Manual.Templates.Api.Api_HostAddress}}/api/demo/3

###
